- ansible/group_vars/all
- ansible/roles/dashd/templates/dash.conf.j2
- networks/devnet-example.yml
https://dashpay.atlassian.net/browse/DD-332
> Make DashCore RPC publicly available (optionally)

- terraform/aws/main.tf
- terraform/aws/variables.tf
https://dashpay.atlassian.net/browse/DD-334
> Configure AWS network to make all needed ports available publicly (temporary)

- ansible/roles/mn-insight/tasks/main.yml
- ansible/roles/mn-insight/templates/bitcore-node-dash.json.j2
- ansible/roles/mn-insight/templates/docker-compose.yml.j2
Use compartible with dashevo/insight and dashevo/evoinsight config format
> Use compatible version of insight config

- ansible/deploy.yml
- ansible/roles/docker-options/files/docker.socket
- ansible/roles/docker-options/tasks/main.yml
- ansible/roles/mn-evo-services/tasks/ipfs/get_bootstrap_peer_id.yml
- ansible/roles/mn-evo-services/tasks/main.yml
- ansible/roles/mn-evo-services/templates/docker-compose.yml
- ansible/roles/mn-insight/tasks/main.yml
- ansible/roles/mn-insight/templates/docker-compose.yml.j2
- ansible/roles/mn-sentinel/templates/docker-compose.yml
- terraform/aws/templates/services/services.tpl
There are two issues:
- New Docker Compose randomizes container names
- https://github.com/ansible/ansible/issues/47978
> Fix ansible roles after upgrading Docker

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
> feat: remove data contract restriction option

- Dockerfile
Upgrade Terraform to 0.12.26
Updated a version of Terraform in the Docker file.
Deployed Palinka with the new version of Terraform.
None
> feat: upgrade Terraform to 0.12.26

- ansible/roles/swap/tasks/main.yml
change swappiness value to avoid not necessary swap usage
> fix: swappiness value is too big

- ansible/roles/swap/tasks/main.yml
we want to reset swap usage after swappiness config change
> feat: reset swap usage when changing swap options

- ansible/group_vars/all
Original image was having issue during container creation and was creating additional wrong volumes.
Updated `Tendermin` image name to `dashpay/tendermint`
Separately in `mn-bootstrap` and `test-suite`
None.
> fix: invalid volumes were added during Tendermint container creation

- ansible/roles/mn-evo-services/tasks/main.yml
Get Tendermint node ID output contains docker-compose pull output as well
Pull images before we run get Tendermint node ID command
> fix: dirty get Tendermint node ID output

- ansible/deploy.yml
Prune not just redundant images but other unused docker data after deploy
Use `docker system prune -a` instead of `docker image prune`.
With deploy.
None
> feat: prune all unused docker data

- .mocharc.yml
- package-lock.json
- package.json
- test/.eslintrc
- test/mocha.opts
In order to make mocha testing consistent across components devs will need to  update the outdated version of mocha
mocha updated to 7.2.0
updated outdated config
None
> test: update mocha to 7.2.0

- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Due to `lastBlockHeaderTime` is for the last committed block, we should generate empty blocks within block window.
- Updated `Tendermint` config files to generate empty blocks
Local dev env
None.
> feat: generate empty blocks every 3 minutes

- package-lock.json
- package.json
Updated version for release
Updated version for release
None.
> chore: bump version to `0.15.0-dev.1`

- karma.conf.js
- package-lock.json
- package.json
- test/smoke/dapi.js
- test/smoke_web/dapi.js
Update DAPI Client to the latest version
DAPI Client updated to 0.15.0-dev.4
Running smoke tests
None
> feat: update DAPI Client to 0.15

- ansible/roles/mn-evo-services/templates/dapi-envoy.yaml.j2
- ansible/roles/mn-evo-services/templates/dapi-nginx-grpc.conf.j2
- ansible/roles/mn-evo-services/templates/dapi-nginx.conf.j2
As we've moved `subscribeToTransactionsWithProofs` to `Core` service, we need to update configs
Updated `nginx` and `envoy` configs
> feat: move `subscribeToTransactionsWithProofs` to `Core` service

- package-lock.json
- package.json
Updating version for a release
Updating version for a release
> chore: update version to 0.15.0-dev.2

- terraform/aws/instances.tf
Nodes don't have enough memory and utilize swap usually. That's not great.
AWS EC2 instance type changed from small to medium.
None
This change leads to redeploy the infrastructure of existing networks.
> fix!: increase masternode size

- ansible/roles/mn-evo-services/templates/dapi-nginx-grpc.conf.j2
- ansible/roles/mn-evo-services/templates/dapi-nginx.conf.j2
Nginx should handle API requests for undefined versions. * To do so we need to add a location with wildcard instead of version and respond with UNIMPLEMENTED (12) gRPC status code.
Changed nginx configs
Manually
None
> feat: nginx responds with unimplemented in case if version is not supported

- README.md
Brings readme into [standard-readme](https://github.com/RichardLitt/standard-readme) compliance
N/A
N/A
> docs: readme update for standard complience

- ansible/roles/docker-options/defaults/main.yml
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
We need to improve logging
- Set debug log level for Drive by default
- Set development environment for DAPI and Drive by default
- Increased docker logs limit up to 768m per file
No
No
> feat: enable debug log, error reporting and increase docker logs limit

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
It's pretty dangerous to have development env by default. Also, logging level debug is too verbose for production.
Add variable `node_environment=production`
Add variable `drive_loggin_level=info`
None
None
> feat: variables for env and logging level

- ansible/roles/dashd/templates/dash.conf.j2
With Core 0.16 a required network section introduced to dashd config.
Added network section to dashd config.
None
DashCore 0.15 is not supported anymore.
> feat!: update dashd config for DashCore 0.16

- package-lock.json
- package.json
- test/smoke/dapi.js
- test/smoke_web/dapi.js
Update to DAPI Client to 0.16
Updated DAPI Client to 0.16
With smoke tests
None
> chore: update DAPI Client to 0.16

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
Drive except DPNS contract ID requires block height on which the contract was created to verify existence.
Introduced a new variable `platform_dpns_contract_block_height`
None
`platform_dpns_contract_block_height` is required if `platform_dpns_contract_id` is set
> feat: pass DPNS contract block height to Drive

- bin/generate-configs.js
- lib/configGenerator/generateAnsibleConfig.js
- lib/configGenerator/generateTerraformConfig.js
Generate command doesn't create configs files
Chose the right directory to write files.
None
None
> fix: generate command doesn't create configs

- ansible/group_vars/all
- ansible/roles/activate-dashd-sporks/tasks/main.yml
- ansible/roles/dashd/templates/dash.conf.j2
add support for dash 0.17
Update images and config templates
Tested on testnet
> feat: support dash 0.17

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
Added dashpay environment variables
No
> feat: add dashpay environment variables

- ansible/group_vars/all
- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/mn-evo-services/tasks/tendermint.yml
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
- ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
To support new Drive and Tenderdash we need to pass additional options and rename tendermint cli to tenderdash
- Rename tendermint cli to tenderdash
- Pass initial core chain locked height to bootstrap the platform network
None
Requires Drive 0.17 and Tenderdash
> feat: update to platform v0.17

- ansible/roles/mn-createprotx/tasks/main.yml
> fix: rescan after import for owner keys

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
- ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
Having to much of validators right now, we decided to introduce `maximum validators` configuration value.
- added `tenderdash_max_validators_count` with the default of `50`
- `config.toml` and `genesis.json` are affected
None.
> feat: introduce maximum validators configuration value

- ansible/roles/mn-init/tasks/main.yml
mn-init role throws templating error: "test true not found"
Used `json_query` filter to get value of `isSynced` property
With deploy
None
> fix: templating issue test true not found

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.17
- Updated changelog
- Bump version
None
None
> chore(release): update changelog and bump version to 0.17.0

- ansible/deploy.yml
- ansible/group_vars/all
- ansible/roles/mn-evo-services/tasks/main.yml
- ansible/roles/mn-evo-services/tasks/tendermint.yml
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
- ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
- ansible/roles/mn-evo-services/vars/main.yml
- karma.conf.js
- terraform/aws/ansible_inventory_output.tf
- terraform/aws/instances.tf
- terraform/aws/monitoring.tf
- terraform/aws/services_output.tf
- terraform/aws/templates/inventory/ansible_inventory.tpl
- terraform/aws/templates/services/services.tpl
- terraform/aws/variables.tf
- test/smoke/core.js
- test/smoke/drive.js
Persistent peers for Tendermint doesn't work on large scale networks since nodes have limitations for peer connections since they are resource consuming. The right approach is to introduce seeds.
- Allow to setup many seed nodes
- Increase seed node AWS instance to `t3.medium`
- Setup platform full node with seed mode enabled on seed nodes
- Set seeds instead of persistent peers for masternode tenderdash nodes
Deployed Palinka with seed nodes and ran smoke tests
- `full_nodes` group is removed from ansible inventory in favor of `seed_nodes`
- `node_count` TF variable is removed in favor of `seed_count`
- genesis time is getting from seed node instead of masternode-1
> feat!: seed nodes

- ansible/deploy.yml
- ansible/group_vars/all
- ansible/requirements.yml
- ansible/roles/mn-evo-services/tasks/main.yml
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
After each Docker image update, related containers are recreated and logs are missed. 
- Add Drive logging options to configure specific log type level:
- `drive_log_stdout_level: info`
- `drive_log_pretty_file_level: silent`
- `drive_log_json_file_level: silent`
- Rotate logs
Deploying on testnet
`drive_logging_level` is removed. Use `drive_log_stdout_level` instead
> feat!: Drive log files

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
To activate feature flags we need to pass contract id, height and identity to Drive
- Pass feature flags contract id, block height and identity variables to Drive
None
None
> feat: feature flags

- test/smoke/dapi.js
Smoke test was failing with `AssertionError: expected { Object (version, time, ...) } to have property 'sync_progress'`
Change property syntax to `syncProgress`
On palinka
None
> fix: don't use snake_case for property

- .github/workflows/release.yml
The docker metadata action moved
Update metadata action target
in CI
None
> ci: update metadata action repo

- package-lock.json
- package.json
- test/smoke/dapi.js
- test/smoke_web/dapi.js
Update DAPI Client to v0.20
- Handle `NOT_FOUND` errors for getDataContract requests in smoke tests
None
None
> chore: update DAPI Client to v0.20

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.20.0
- Update changelog
- Bump version to 0.20.0
None
None
>  chore(release): update changelog and bump version 0.20.0

- package-lock.json
- package.json
grpc-common version was updated
Update grpc-common dep versions
In CI
> chore: bump grpc-common deps

- Dockerfile
- README.md
- terraform/aws/.terraform.lock.hcl
- terraform/aws/ansible_inventory_output.tf
- terraform/aws/main.tf
- terraform/aws/services_output.tf
- terraform/aws/templates/services/service.tpl
- terraform/aws/versions.tf
It made sense to upgrade to a stable Terraform version before increasing complexity by adding modules.
- Update Terraform to `1.0.5`
- Update plugins and apply version lock
- Update Terraform files to use stable syntax
Tested against `devnet-schnapps` and `testnet`, state files updated in S3.
Minimum Terraform version is now `1.0.5`. Older versions of Terraform will fail against both the config files and state files. Recommend using [tfenv](https://github.com/tfutils/tfenv) to install terraform.
> chore: update terraform to version 1.0.5

- ansible/deploy.yml
- ansible/group_vars/all
- ansible/roles/add-fake-latency/tasks/main.yml
- ansible/roles/remove-fake-latency/tasks/main.yml
To add "random" latency at the network level to the masternode servers through Ansible in order to test Platform under latency more similar to how mainnet operates. This will apply to devnet/testnet only
* Two roles have been added to ansible as the underlying Linux command is not atomic
* The first is to add network latency if latency == 1 in the ansible vars
* The second will set the latency to nothing if latency variable is 0 (This is so each command can run atomically)
This is achieved using qdiscs (Linux traffic control) and applies to all traffic to and from the masternode in question. Once you set latency to 1 it will apply to all masternodes
Note that right now we are simply using a shell command to achieve this as there is no underlying Ansible module which can add latency. This …
> feat: atomic latency option added to Ansible

- .github/workflows/release.yml
ARM64 build was failing for unknown reason
Remove ARM64 build
Locally
None
> ci: remove arm64 builds

- package-lock.json
- package.json
Version needed bumping for pre-release
Bump version to 0.21.0-dev.4
In CI
None
> chore: bump version 0.21.0-dev.4

- Dockerfile
- package-lock.json
- package.json
We need to update to node 16
- Update package to node 16
- Run tests
- Update CI
In CI and against schnapps
None
> chore: update package for node 16

- package-lock.json
- package.json
Bump version for release
Bump version to 0.21.0-dev.5
In CI
None
> chore: bump version to v0.21.0-dev.5

- ansible/deploy.yml
- ansible/group_vars/all
- ansible/requirements.yml
- ansible/roles/elastic-beats/tasks/main.yml
- ansible/roles/elastic-stack/files/index-templates/logs-drive.abci.json
- ansible/roles/elastic-stack/files/index-templates/logs-drive.tenderdash.json
- ansible/roles/elastic-stack/tasks/configure-cluster.yml
- ansible/roles/elastic-stack/tasks/generate-certs.yml
- ansible/roles/elastic-stack/tasks/main.yml
- ansible/roles/elastic-stack/tasks/volume.yml
- ansible/roles/elastic-stack/templates/certs/.env.j2
- ansible/roles/elastic-stack/templates/certs/docker-compose.yml.j2
- ansible/roles/elastic-stack/templates/certs/instances.yml.j2
- ansible/roles/elastic-stack/templates/docker-compose.yml.j2
- ansible/roles/elastic-stack/templates/elasticsearch.yml.j2
- ansible/roles/elastic-stack/vars/main.yml
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
- lib/configGenerator/generateAnsibleConfig.js
- lib/configGenerator/generateTerraformConfig.js
- terraform/aws/instances.tf
- terraform/aws/variables.tf
Logging multiple services at maximum verbosity was quickly filling up a single Elasticsearch node due to AWS limitations on block storage size.
Implement Elasticsearch cluster and enable production mode and TLS on communication between nodes
By deploying a new network to test the cluster feature
> feat: implement elasticsearch cluster

- ansible/deploy.yml
Accidentally committed commented deploy file
Uncomment deploy.yml
> chore: uncomment deploy.yml

- ansible/group_vars/all
- ansible/requirements.yml
- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/elastic-beats/tasks/main.yml
- ansible/roles/elastic-stack/files/index-templates/logs-core.json
- ansible/roles/elastic-stack/tasks/configure-cluster.yml
- ansible/roles/elastic-stack/tasks/generate-certs.yml
- ansible/roles/elastic-stack/tasks/main.yml
- ansible/roles/openvpn/tasks/main.yml
- lib/configGenerator/generateAnsibleConfig.js
- lib/configGenerator/generateTerraformConfig.js
- terraform/aws/variables.tf
Core team need more detailed logging to debug devnets
- use latest elasticsearch version 7.16.0
- increase default aws node and jvm heap size
- increase minimumdifficultyblocks to support DIP24
- add core logs index template and data stream
- fix various typos and timing bugs discovered during `devnet-malort` deployments
While deploying `devnet-malort` multiple times
None
> feat: add core logs to elasticsearch

- .gitignore
- lib/cli/init.sh
- networks/.gitignore
It is necessary to be able to symlink the networks dir without it appearing in the list of git changes, which results in it accidentally being committed.
Delete networks dir and add to `.gitignore` so symlinks are not seen
Locally
`networks` dir no longer exists (but will be generated if not manually created or symlinked)
> chore: ignore networks dir

- lib/configGenerator/generateAnsibleConfig.js
- lib/configGenerator/generateTerraformConfig.js
It was not possible to immediately use a generated config because some blank values were generated
- Remove settings with blank default values from config (engineer can re-add these as necessary)
- Expose `dashd_debug` with default of `0` in config
Locally
None
> chore: fix template defaults

- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
Compose commands were failing when deploying `v0.22-dev` platform images
Modify `npm run` commands to `yarn workspace`
On krupnik
Cannot deploy `0.21.x` images anymore, so this will only be merged once `v0.22.x` is live on testnet.
> fix: modify compose commands to use yarn

- ansible/roles/mn-evo-services/templates/docker-compose.yml.j2
Fix for docker compose for v0.22.0-dev6 onwards
Renamed tx-stream to core-streams in dapi so network deploy tool needs to now use this name.
Change linked here: https://github.com/dashevo/platform/pull/169/files
Deployed devnet-krupnik
None
- [x ] I have added or updated relevant unit/integration/functional/e2e tests
> chore: update docker compose

- ansible/roles/mn-init/tasks/main.yml
I've modified the checks to not use mnsync status to check if the blockchain in synced as this can take up to an hour. Instead we check if headers == blocks (or we can check if verification > 0.99 if preferred)
Once synced we force mnsync next twice, checking each time that it's taken. Much like Dashmate does now
* Check blocks are synced
* Force mnsync next twice (once for the chain, once for the governance objects)
* Check the results
Deployed devnet-echo to test, worked like a charm.
None
> feat: speed up masternodes syncing

- ansible/roles/mn-evo-services/templates/dapi-envoy.yaml.j2
- ansible/roles/mn-evo-services/templates/dapi-nginx-grpc.conf.j2
- ansible/roles/mn-evo-services/templates/dapi-nginx.conf.j2
subscribeToBlockHeadersWithChainLocks endpoint is not reachable
- Added configuration for `subscribeToBlockHeadersWithChainLocks` endpoint
None
None
> fix: subscribeToBlockHeadersWithChainLocks is not reachable

- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Tenderdash 0.7.0 requires `create_proof_block_range` to be defined
Set `create_proof_block_range = 1`
On testnet
None
> chore: add create_proof_block_range to td config

- package-lock.json
- package.json
- test/smoke/core.js
Smoke tests aren't compatible with new Core and DAPI Clients
- Updated deps
- Changed network signature
Running tests
None
> fix: smoke tests are failing

- CHANGELOG.md
- TODO.md
- package-lock.json
- package.json
Release v0.22.0 
- Bumped version
- Updated changelog
None
None
> chore(release): update changelog and version to v0.22.0

- ansible/group_vars/all
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Tenderdash logs need to have different settings on different network
Allow definition of `tenderdash_log_level` in settings, define `debug` as default
On testnet
None
> feat: make tenderdash log_level configurable

- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
- lib/configGenerator/generateAnsibleConfig.js
Now that quorum rotation is out of alpha testing, we will primarily be deploying networks with QR. This PR adds settings to make deploying this type of network easier.
- add `llmqinstantsenddip0024=llmq_devnet` to devnets
- set logips if debugging dashd
- set `minimumdifficultyblocks` from config
On devnet-malort
> feat: changes to support devnets with quorum rotation

- ansible/group_vars/all
- ansible/requirements.yml
A security audit revealed Elastic tools should be updated to 7.16.2+ for compliance with measures needed to mitigate the Log4j vulnerability. 
Update to Elastic 7.17.0. This is the last release in the 7.x series, future updates will require more detailed exploration.
On `devnet-sangsom`
None, all previously collected data remains available
> chore: update elastic stack to 7.17.0

- ansible/roles/openvpn/tasks/main.yml
- terraform/aws/main.tf
Ubuntu 18.04 is slowly aging out of the general support cycle, and does not support `arm64` arch as well as newer ubuntu versions. We should update to the latest Ubuntu LTS release to fix this.
- Update Ubuntu base image to 22.04 Jammy Jellyfish
- Remove unneeded external repo source to install OpenVPN (jammy already includes a very recent version)
Tested by deploying a small new devnet (still only tested on x86_64)
> chore: update base image to ubuntu 22.04

- ansible/deploy.yml
- ansible/requirements.yml
- ansible/roles/multifaucet/templates/multifaucet/Dockerfile
- ansible/roles/openvpn/tasks/main.yml
- lib/configGenerator/generateTerraformConfig.js
- terraform/aws/instances.tf
- terraform/aws/main.tf
- terraform/aws/variables.tf
Running on `arm64` AWS Graviton 2 instances is significantly cheaper than equivalent `x86_64` instances. We should deploy devnets on `arm64` to save costs.
- implement config and conditional logic in terraform
- pin several dependency versions for installed software
On 2x small devnets, one `arm64` and one `x86_64`, both install with no issues
None
> feat: arm64 nodes

- terraform/aws/versions.tf
> chore: bump terraform version

- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Tenderdash 0.8 has requires some changes to configs
- Renamed fastsync section to blocksync
On devnet-krupnik
No longer supports Tenderdash < 0.8
> feat!: tenderdash 0.8 support

- test/smoke/core.js
- test/smoke/sentinel.js
All tests except core were disabled, which means we were not receiving enough information on the status of our devnets when running tests in CI.
- Remove `.only` from core tests
- Remove `.skip` from sentinel tests
Against `devnet-333`, all smoke and smoke_web tests pass with 100% success.
None
> chore: enable all tests

- package-lock.json
- package.json
We need to release a version in order to build an image with parallelization fixes.
Bump version to 0.22.1
> chore: bump version to 0.22.1

- ansible/roles/dashd/templates/dash.conf.j2
Dash Core now supports the `powtargetspacing` setting
- Add powtargetspacing
On `devnet-jack-daniels`
None
> feat: add powtargetspacing to dash.conf vars

- ansible/roles/dashd/templates/dash.conf.j2
The syntax for this setting has changed:
Until 18.0.0.rc6 `llmqinstantsenddip0024=llmq_devnet`
From 18.0.0.rc7 `llmqinstantsenddip0024=llmq_devnet_dip0024`
Update syntax
Won't work with ≤18.0.0-rc6
> chore: update llmqinstantsenddip0024 syntax

- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Tenderdash was complaining about: `ERROR: failed to parse log level (*:debug): Unknown Level String: '*:debug', defaulting to NoLevel`
Modify syntax according to Tendermint docs
None
> fix: failed to parse log level (*:debug)

- test/smoke/dapi.js
DAPI smoke tests were taking 25 minutes to run against testnet
- Parallelize tests (20x speedup, run time 1m10s)
- Output DAPI Client errors
Against testnet
None
> perf: speedup dapi

- ansible/group_vars/all
- ansible/requirements.yml
Accidental use of the v0.23 branch on testnet a few months ago means replays of the `elastic-beats` role will result in an error from apt complaining about an illegal downgrade from 7.17 to 7.16.
Backport #295 
On testnet
None, Elastic upgrades cleanly
> chore: backport elastic 7.17

- terraform/aws/instances.tf
- terraform/aws/variables.tf
Testnet wallet infrastructure was provisioned too small, nodes were unresponsive
Make wallet node type configurable
On testnet
> chore: add setting for wallet node type

- package-lock.json
- package.json
We need to release a version for use in CI.
Bump version to 0.22.2
> chore: bump version to 0.22.2

- ansible/roles/mn-sentinel/templates/docker-compose.yml
Sentinel debug output was causing smoke tests to fail
Disable debug output
On testnet
None
> chore: disable sentinel debug

- ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Extra block production (in case if app hash is changed) in tenderdsah is unnecessary anymore and lead to infinite blocks. Read more https://github.com/dashevo/platform/pull/484
- Set `create-proof-block-range` to `0` to disable extra block production
Deployment on devnet
DAPI v0.22 and less aren't supported
> feat!: disable extra block production in tenderdash

- bin/dash-network
Drive tests use a new magic string to test echo, so we need to differentiate between branches when building images for CI
Specify `latest-dev` when running from dev branch
Need to ensure this gets replaced this when merging for stable release
> fix: tests running from wrong branch

- package-lock.json
- package.json
We need to release a dev version to run tests again 0.23 devnets in CI
Release `0.23.0-dev.1`
> chore: bump version to 0.23.0-dev.1

- test/smoke/elastic.js
- test/smoke/index.spec.js
Smoke tests did not test the elastic logging cluster
Write test for logs servers
On testnet
> feat: elastic tests

- ansible/roles/dashd/tasks/main.yml
Core logs were filling up the miner node on devnet-jack-daniels until it ran out of disk space.
Add logrotate to core debug.log
Tested on devnet-filebeat
None
> fix: logrotate core

- ansible/roles/mn-createprotx/tasks/createprovidertx.yml
Wallets on testnet were becoming enormous because we were mining to the faucet address
Mine to a separate address and manually fund faucet when necessary
Untested
> fix: don't pay coinbase to faucet address

- ansible/roles/dashd/tasks/main.yml
We need to enable core debug mode on testnet, so need this code in master as well
Add logrotate to core debug.log
Tested on devnet-filebeat
None
> feat: logrotate for core debug.log

- ansible/roles/multifaucet/tasks/main.yml
- ansible/roles/multifaucet/templates/multifaucet/Dockerfile
- ansible/roles/multifaucet/templates/multifaucet/faucet.conf.php
`faucet.testnet.networks.dash.org` did not support promo codes
Enable promo codes
On testnet
None
> feat: multifaucet promo codes

- ansible/roles/dashd/templates/dash.conf.j2
DAPI TX Stream requires [rawblock](https://github.com/dashevo/platform/blob/v0.23-dev/packages/dapi/scripts/core-streams.js#L108) ZMQ topic to be enabled in order to deliver fresh merkle blocks to JS wallet
> fix: add zmqpubrawblock topic to the dash.conf

- ansible/roles/dashd/templates/dash.conf.j2
DAPI TX Stream requires [rawblock](https://github.com/dashevo/platform/blob/master/packages/dapi/scripts/core-streams.js#L105) ZMQ topic to be enabled in order to deliver fresh merkle blocks to JS wallet
> fix: add zmqpubrawblock to dash conf testnet

- package-lock.json
- package.json
Need to release a new version to run in CI
Bump version to 0.22.3
> chore: bump version to 0.22.3

- ansible/roles/dashd/tasks/main.yml
Containers sometimes needed reindexing after shutdown/restart.
Increase shutdown timeout
Untested
None
> fix: reindex needed after restart

- terraform/aws/instances.tf
- terraform/aws/variables.tf
Inventory did not match config, despite config apparently being defined correctly. Turns out node size/type vars were getting confused.
Fix variable naming and node type selection logic
On testnest
None
> fix: node type vars inconsistent with config

- .github/workflows/release.yml
Many action deps have been updated in preparation of the Node 12 deprecation, and we were beginning to see other warnings:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
We need to update many of these actions in platform and other repos soon, so I would like to test them here first for any obvious changes.
Update deps
In testing
> ci: update deps

- package-lock.json
- package.json
CI was updated in #371. We need to test it by doing another release before applying same/similar CI to `dashpay/platform`
Bump version to 0.23.0-dev.3
This is testing
None
> chore: bump version to 0.23.0-dev.3

- bin/generate-configs.js
I wasted a bunch of time by accidentally generating a config with a negative masternode count.
Add a sanity check for vars passed to `bin/generate`
Manually by running all possible variants
None
> chore: basic sanity check of input values

- ansible/deploy.yml
- ansible/roles/dashd/tasks/create-wallet.yml
- ansible/roles/dashd/tasks/main.yml
- ansible/roles/multifaucet/tasks/main.yml
Dash Core 18.2.0 contains a breaking change relating to wallet creation
Implement wallet creation logic
On `devnet-blink-182`
None, this should still work with older versions.
> chore: explicitly create wallets for core 18.2

- terraform/aws/main.tf
- terraform/aws/security_groups.tf
- terraform/aws/services_output.tf
- terraform/aws/variables.tf
Insight must be served with TLS for some tests to run correctly.
Install TLS cert on ELB
Testing on `devnet-acm`
> feat: insight acm certs

- ansible/roles/elastic-stack/tasks/main.yml
Deploy tool would intermittently fail during logs deploy with a Kibana error
Check harder to make sure Kibana is actually ready
On a custom devnet
None
> fix: kibana unavailable despite passing check

- ansible/destroy.yml
- ansible/roles/dashd/tasks/main.yml
- ansible/roles/kill-platform/tasks/main.yml
- bin/destroy
- lib/cli/ansible.sh
We frequently need to destroy platform layer on masternodes and seed nodes and redeploy platform. This was previously achieved with a long and unwieldy command like this: 
`ANSIBLE_HOST_KEY_CHECKING=false ansible masternodes,seed_nodes -i networks/devnet-jack-daniels.inventory --private-key=/home/strophy/.ssh/evo-app-deploy.rsa -b -m shell -a "cd /dash/mn_evo_services/ && docker-compose down -v && rm -rf logs/* && rm -rf tendermint && docker volume prune -f"`
:fearful: 
Implement above command as ansible role and update destroy playbook and wrapper.
Against `devnet-dstry`
None
> feat: destroy platform

- ansible/deploy.yml
- ansible/roles/dashd/tasks/create-wallet.yml
- ansible/roles/dashd/tasks/main.yml
- ansible/roles/generate-blocks/tasks/regtest_generate.yml
- ansible/roles/mn-createprotx/tasks/createprovidertx.yml
- ansible/roles/mn-createprotx/tasks/main.yml
- ansible/roles/mn-fund-collateral/tasks/fund_collateral.yml
- ansible/roles/mn-fund-collateral/tasks/main.yml
Deploying networks can be very slow, particularly with very large networks
Refactor `fund_collateral.yml` to take different args and use the `sendmany` command
In testing
> feat: create funding transactions faster using `sendmany`

- ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
Drive crashed on startup with:
```
err: {
"type": "NetworkProtocolVersionIsNotSetError",
"message": "Network protocol version is not set",
...
```
Add `app_version` to `genesis.json`
> chore: update genesis.json app_version

- test/smoke/core.js
Smoke tests were regularly failing due to normal variance in block production times
Rewrite test logic. Old logic was to wait for a block to appear on each miner. New logic:
- look back over last 10 blocks and calculate average time, and verify this is within expected target tolerance
- verify that at least one block was created in the last 10 minutes
Against `testnet` and `devnet-jack-daniels`
None
> feat: check recent mining performance instead of waiting for blocks

- .github/workflows/test.yml
- ansible/requirements.yml
Deploy tool code base was recently updated to conform with Ansible Schemas. We want to maintain these coding standards going forward.
Run `ansible-lint` in CI
In CI
None
> ci: run ansible-lint

- ansible/roles/mn_protx_config/tasks/find_protx.yml
- ansible/roles/mn_protx_config/tasks/main.yml
- ansible/roles/mn_unban/tasks/find_protx.yml
- bin/deploy
A few missing pieces of docs/bugs needed cleaning up after merging #390 
- Clean up unnecessary/incorrect comments and debug code
- Reset a variable that may potentially already contain data
On `devnet-jack-daniels`
None
> fix: inventory is updated twice

- ansible/roles/multifaucet/templates/config/faucet.conf.php
The faucet was probably checking the IP address of a proxy to see if payout was permitted
Set faucet to check address only
Testnet
> fix: faucet doesn't pay out

- ansible/destroy.yml
- ansible/group_vars/all
- ansible/roles/elastic_stack/vars/main.yml
- ansible/roles/kill_logs/tasks/main.yml
- ansible/roles/kill_network/tasks/main.yml
- bin/destroy
Manual work was necessary to properly reset the elasticsearch logs cluster
Implement `logs` as target of destroy command
On testnet
None
> feat: logs destroy target

- ansible/roles/multifaucet/templates/docker-compose.yml.j2
The faucet would show a connection error instead of paying out.
Remove `""` from wallet unlock config, this was being sent as a literal.
On jack-daniels
None
> fix: faucet shows connection error on payout

- package-lock.json
- package.json
We need to release a new version with updates tests to run against testnet
Bump version to `0.23.0-dev.4`
This is for testing
None
> chore: bump version to 0.23.0-dev.4

- ansible/roles/dashd/templates/dash.conf.j2
Adding a `uacomment` can help devs and external users identify which servers they are connected to, which is useful for debugging.
Add `uacomment` to `dash.conf`
On testnet `masternode-111`: 
```
root@masternode-111:/dash/dashcore# dash-cli getnetworkinfo
{
"version": 180200,
"buildversion": "v18.2.0-rc.2",
"subversion": "/Dash Core:18.2.0(dcg-masternode-111)/",
"protocolversion": 70224,
...
```
None
> chore: add uacomment to dash.conf

- test/smoke/core.js
Some RPCs take a really long time to return on testnet at the moment. https://github.com/dashpay/dash/pull/5100
Increase timeout
Locally
None
> fix: miner-2 smoke test timeout

- package-lock.json
- package.json
Need to release 0.23.1 to fix network CI
Bump version
Locally
None
> chore: release 0.23.1

- ansible/roles/mn_evo_services/templates/tendermint/config.toml.j2
Seed nodes need to behave differently with Tenderdash 0.10.0-dev.7
Update Tenderdash seed parameters in `config.toml`
Untested
Won't work with Tenderdash < 0.10.0-dev.7
> chore: modify tenderdash seed p2p parameters

- ansible/deploy.yml
- ansible/roles/dashd/templates/dash.conf.j2
Change the order of masternodes deploymen: masternode deployment should come after the registration. 
* Put masternodes deployment after the proreg tx registration
* Merged core and platform tasks into single task
Deployed network via this tool and ensured that all nodes became READY. Also checked elasticsearch logs after all.
None
> feat: reorder masternodes order

- ansible/roles/mn_evo_services/templates/tendermint/config.toml.j2
Tenderdash seed nodes weren't behaving correctly with short timeouts
Increase timeouts
On `devnet-bintang`
None
> chore: increase timeouts

- lib/configGenerator/generateAnsibleConfig.js
Different networks should be tested at different rates, so we should specify this (and a sensible default) in config.
Add `smoke_test_st_execution_interval`
Testnet
None
> chore: add smoke_test_st_execution_interval to config

- package-lock.json
- package.json
- test/smoke/index.spec.js
- test/smoke/quorum.js
Smoke tests should also check the status of quorums.
Add tests to check for:
- formation of the proper quorum types
- presence of chainlocks at the chain tip
- recency of the first quorum of an appropriate type for the target network
- presence of IS locks after creating a transaction
Locally, against `devnet-bintang`
None
> feat: add quorum smoke tests

- .dockerignore
- Dockerfile
- bin/deploy
The Docker image contains Terraform `1.0.5` which is lower than the version constaint `~> 1.2`.
Update version deps for tools used in the Dockerfile, fix errors discovered during testing
Locally against `devnet-bintang`
None
> chore: update dockerfile version deps

- ansible/group_vars/all
New quorum type was observed
Add the quorum type to vars list
Untested
None
> chore: add quorum type llmq_60_75

- ansible/roles/mn_evo_services/templates/tendermint/config.toml.j2
New tenderdash config for seed nodes from tenderdash team
Changed variables in config.toml
on devnet-bintang
None
> chore: new tenderdash config for seednodes

- ansible/roles/multifaucet/templates/config/faucet.conf.php
- ansible/roles/multifaucet/templates/docker-compose.yml.j2
[Multifaucet 0.9.0 is available](https://github.com/dashpay/multifaucet/releases/tag/v0.9.0) with support for recaptcha v2
Implement new vars to pass secrets to new version of multifaucet
On testnet
None
> feat: use new recaptcha methods available in multifaucet 0.9.0

- terraform/aws/main.tf
- terraform/aws/security_groups.tf
- terraform/aws/variables.tf
HTTPS was requested for the faucet deployed by deploy tool
Add ACM cert and HTTPS port to ELB
On a test deployment
None
> feat: faucet tls

- ansible/group_vars/all
- ansible/roles/dashmate/defaults/main.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- ansible/roles/docker_options/handlers/main.yml
- ansible/roles/kill_network/tasks/main.yml
- ansible/roles/mn_evo_services/templates/docker-compose.yml.j2
- ansible/roles/mn_evo_services/templates/tendermint/config.toml.j2
- karma.conf.js
- lib/cli/test.sh
- lib/configGenerator/generateAnsibleConfig.js
- lib/test/createRpcClientFromConfig.js
- lib/test/docker.js
- lib/test/getNetworkConfig.js
- package-lock.json
- package.json
- terraform/aws/instances.tf
- terraform/aws/security_groups.tf
- terraform/aws/services_output.tf
- terraform/aws/variables.tf
- test/smoke/core.js
- test/smoke/dapi.js
- test/smoke/drive.js
- test/smoke/elastic.js
- test/smoke/faucet.js
- test/smoke/insight.js
- test/smoke/quorum.js
- test/smoke/sentinel.js
- test/smoke/tendermint.js
- test/smoke_web/dapi.js
Make smoke tests work for nodes running dashmate
* Fix all tests according new infrastructure
* Enable HTTPS support for DAPI smoke tests
* Query via remote docker instead of querying service RPC ports (they are intentionally closed for security reasons)
Smoke tests on the running devnet
No
> feat: enable smoke tests with dashmate

- ansible/roles/dashd/templates/dash.conf.j2
Need to `llmqplatform` setting for devnets on v19
Add `llmqplatform` setting for devnets
On `devnet-white-russian`
None
> chore: add llmqplatform default for devnets

- ansible/roles/multifaucet/templates/config/faucet.conf.php
We forgot to update the generated config to match changes made in multifaucet v0.9.1.
Config now correctly configures recaptcha_v2
On testnet
None
> chore: enable recaptcha_v2

- terraform/aws/instances.tf
The testnet infra plan specifies logs nodes should run on aws x2gd type nodes
Update logs node type
On testnet
IP address of logs cluster will change during node type migration, need to update filebeat
> chore: deploy logs nodes on aws x2gd type infra

- ansible/roles/activate_dashd_sporks/tasks/main.yml
- ansible/roles/dashd/tasks/main.yml
- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/multifaucet/templates/config/faucet.conf.php
- ansible/roles/multifaucet/templates/docker-compose.yml.j2
- terraform/aws/main.tf
- terraform/aws/security_groups.tf
- terraform/aws/variables.tf
- test/smoke/core.js
Some features implemented on `master` branch were missing from `v0.24-dev`
- Merge `master` into `v0.24-dev
- Fix logrotate issue
Don't squash merge this one
On testnet
None
> chore: merge master

- ansible/deploy.yml
- ansible/group_vars/all
- ansible/roles/generate_proposals/tasks/createproposaltx.yml
- ansible/roles/generate_proposals/tasks/main.yml
- lib/configGenerator/generateAnsibleConfig.js
We often encounter errors relating to governance proposals and the superblock on testnet, because this is the first network a build hits where (manually created) governance proposals exist.
Implement a system to create and vote on governance proposals as defined in the network config.
On devnet-wr, 5 proposals created
None
> feat: governance proposals

- terraform/aws/instances.tf
- terraform/aws/variables.tf
Devnets and testnets are overprovisioned with storage and could be tightened a bit to reduce cost.
Reduce defaults for volume size
Untested, I'm not even sure if we can apply this without creating new nodes....
Probably need new nodes
> chore: reduce default volume sizes

- ansible/roles/mn_evo_services/templates/docker-compose.yml.j2
- lib/configGenerator/generateAnsibleConfig.js
Platform v0.24-dev.14 introduces withdrawals, so more keys are required
Add withdrawal keys to generator
On devnet-paulaner
None
> chore: add withdrawal keys to config generator

- .eslintrc
- ansible/roles/elastic_stack/tasks/configure_cluster.yml
- package-lock.json
- package.json
- test/smoke/core.js
- test/smoke/dapi.js
- test/smoke/drive.js
- test/smoke/elastic.js
- test/smoke/faucet.js
- test/smoke/insight.js
- test/smoke/quorum.js
- test/smoke/sentinel.js
- test/smoke/tendermint.js
Smoke tests were failing in some cases:
- either hpmn or mn list was empty
- islock transaction tests were failing even if successful
- use nullish coalescing syntax to handle undefined array concatenation
- update eslint to support this syntax
- fix islock tests
On devnet-wr
Doesn't work against v18 anymore
> chore: v19 smoke test fixes

- karma.conf.js
- test/smoke_web/dapi.js
Browser smoke tests were failing due to webpack errors and running against masternodes, which no longer provide DAPI
- Update webpack 5 polyfills
- Run browser smoke tests against HPMN instead of MN
Waiting for network with functioning platform to test
None
> chore: fix browser tests

- package-lock.json
- package.json
We need to build a new release to see if browser smoke tests were fixed
Bump release version
> chore(release): bump version to v0.24.0-dev.4

- Dockerfile
- package-lock.json
- package.json
Browser smoke tests could not run in CI, failing with:
```
Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:
snap install firefox
```
Bypass stupid snap installation with manual install 
Locally
> fix: firefox snap

- ansible/roles/dashmate/templates/dashmate.json.j2
Fix comma being present
Fix comma being present that was ending in bad JSON
devnet-hptest
None, this is a fix :)
> Fix: config comma

- ansible/deploy.yml
Status report script failed to run on HPMNs because it wasn't present
Add status report
On devnet-sam-adams
None
> fix: status report fails on hpms

- package-lock.json
- package.json
Need to release another version to update CI with smoke test fixes
Bump to v0.24-dev.6
Locally
> chore(release): bump version t0 v0.24-dev.6

- ansible/group_vars/all
- ansible/roles/dashmate/templates/dashmate.json.j2
- terraform/aws/variables.tf
Fix some templating
* added default dashd_minimumdifficultyblocks 
* fixed devnet name templating
> fix: correct vars and templating

- ansible/roles/mn_unban/tasks/createproupservtx.yml
Unban transactions would fail with `Expecting value: line 1 column 1 (char 0)`
Add txid, not entire result to array of txids
On testnet
None
> fix: Expecting value: line 1 column 1 (char 0)

- Dockerfile
Terraform needed updating to new minimum required version of 1.4.4
Update Dockerfile deps
Locally
None
> chore: update dockerfile deps

- ansible/group_vars/all
Some nodes were already updated to 8.7.0 after testing, so we may need to do this non-breaking update now
Update to 8.7.0
On testnet
None
> chore: update elastic base to 8.7.0

- ansible/roles/dashmate/defaults/main.yml
- ansible/roles/dashmate/tasks/build.yml
- ansible/roles/dashmate/tasks/install.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/tasks/ssl.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- lib/configGenerator/generateAnsibleConfig.js
Currently, you can setup the hp masternode only providing a branch from which dashmate will be built. This approach is pretty convenient when you actively developing/testing dashmate but to slow form common cases. 
- Introduced `dashmate_version` variable to setup a node with dashmate deb package
Manually
None
> feat: install dashmate with deb package

- ansible/roles/mn_unban/tasks/createproupservtx.yml
The condition to check if a masternode protx was available to be added to the list checked the wrong variable.
Use correct variable name.
On testnet
None
> fix: protx is undefined

- ansible/roles/mn_unban/tasks/main.yml
- package-lock.json
- package.json
- test/smoke/quorum.js
IS locks were having timeout issues in CI
Update libs and increase timeout
Against testnet from manager node
None
> fix: is test timeout

- ansible/roles/dashmate/tasks/reset_platform.yml
Platfrom reset tasks stop Core and Sentinel containers as well
- Remove stop task
None
Compatible only with Platform v0.24.0-dev.27 and higher
> fix!: reset platform stops core as well

- ansible/roles/mn_unban/tasks/main.yml
Unban was succeeding, but failing when attempting to show which nodes it was successful on
Update variable name
By succeeding without failing
None
> fix: another broken var in the unban task

- ansible/roles/dashmate/tasks/install.yml
Sometimes we want to install lower version, especially when we had a bug in versioning ;)
- Allow to install lower versions of dashmate package
Manually
None
> feat: allow downgrade dashmate package

- ansible/roles/multifaucet/tasks/main.yml
- ansible/roles/multifaucet/templates/config/faucet.conf.php.j2
- ansible/roles/multifaucet/templates/docker-compose.yml.j2
We don't need to use recaptcha on devnets
Disable recaptcha in faucet if key is not provided
On devnet-bintang
None
> fix: recaptcha unnecessarily required on devnets

- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
Update to recent Platform v0.24-dev
- Configure Core's log file
- Export dot env to enable docker compose commands
- Add some commented convenient tasks
With testnet
None
> chore: update to recent Platform v0.24

- ansible/roles/dashmate/templates/dashmate.json.j2
- ansible/roles/mn_evo_services/templates/tendermint/genesis.json.j2
Drive is too slow to create proposals in time so validators are voting nil due to timeout
- Set genesis tenderdash timeouts
On testnet
Previous platform chaines won't be valid since genesis config is changed.
> fix!: platfrom block proposals too slow

- ansible/roles/dashd/tasks/main.yml
- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/mn_createprotx/tasks/createprovidertx.yml
- ansible/roles/mn_createprotx/tasks/main.yml
- ansible/roles/mn_init/tasks/main.yml
- ansible/roles/mn_protx_config/tasks/main.yml
- ansible/roles/mn_unban/tasks/createproupservtx.yml
- ansible/roles/mn_unban/tasks/main.yml
- ansible/roles/multifaucet/templates/config/faucet.conf.php
- ansible/roles/multifaucet/templates/docker-compose.yml.j2
- package-lock.json
- package.json
- terraform/aws/main.tf
- terraform/aws/security_groups.tf
- terraform/aws/variables.tf
- test/smoke/core.js
> chore: merge master into v0.24-dev

- ansible/roles/dashmate/defaults/main.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- package-lock.json
- package.json
- test/smoke/dapi.js
- test/smoke_web/dapi.js
Self-signed certificates are not supported in web browsers that blocks dapps web development against testnet.
- Setup ZeroSLL certificates for dashmate
Deploying on testnet
None
> feat: ZeroSSL certificates

- package-lock.json
- package.json
We need to release a new version
Bump version to0.24.1
> chore: bump version to 0.24.1

- ansible/roles/dashd/templates/dash.conf.j2
- ansible/roles/elastic_beats/tasks/main.yml
- ansible/roles/elastic_beats/vars/platform.yml
- ansible/roles/elastic_stack/files/index-templates/logs-drive.abci.json
- ansible/roles/kill_network/tasks/main.yml
- ansible/roles/mn_evo_services/templates/docker-compose.yml.j2
Config file syntax has changed for v20 core and v0.25 platform
- Add `fallbackfee`
- Change drive filebeat input template
On `devnet-absinthe`
None
> feat!: core v20 and platform v0.25 updates

- package-lock.json
- package.json
- test/smoke/dapi.js
Incorrect DAPI test targets were accidentally merged
Revert changes to dapi.js
Against testnet
None
> revert: dapi seed tests

- ansible/group_vars/all
- ansible/roles/dashmate/defaults/main.yml
Log permissions were difficult to handle in `/var/log` after restarts
Move logs to dashmate home dir
On testnet
None
> chore: move dashmate logs dir

- ansible/deploy.yml
- ansible/roles/mn_protx_diff/files/protx-diff.sh
- ansible/roles/mn_protx_diff/tasks/main.yml
Core team requested a script specified as:
"Setup a script on 80% of nodes to run `protx diff` with random valid heights once per minute (via cron); continue doing this before and after fork is active; this is for cache invalidation; mimics mobile clients"
Implement a script according to this definition
On testnet
None
> feat: protx diff script

- .github/workflows/test.yml
- Dockerfile
- README.md
- ansible/ansible.cfg
- ansible/deploy.yml
- ansible/group_vars/all
- ansible/requirements.yml
- ansible/roles/dashmate/defaults/main.yml
- ansible/roles/dashmate/tasks/destroy_platform.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/tasks/ssl/self_signed.yml
- ansible/roles/dashmate/tasks/ssl/zerossl.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- ansible/roles/kill_platform/tasks/main.yml
- ansible/roles/mn_protx_diff/files/protx-diff.sh
- ansible/roles/mn_protx_diff/tasks/main.yml
- package-lock.json
- package.json
- terraform/aws/main.tf
- terraform/aws/security_groups.tf
- test/smoke/dapi.js
- test/smoke_web/dapi.js
Changes from `master` are needed on v0.25-dev for testing
Merge `master` into `v0.25-dev`
On testnet
None
> chore: merge master into v0.25-dev

- ansible/roles/dashmate/defaults/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
We need to support performance profiling for tenderdash
Implement changes to dashmate config.json and define default
On testnet
None
> feat: dashmate tenderdash pprof support

- lib/configGenerator/generateAnsibleConfig.js
PR fixes an issue with multiple loadings of wasm BLS into memory. 
It should be loaded only once and then re-used.
Moved BLS loading call outside of the function that called in the loop.
> fix: multiple initilalizations of bls

- ansible/stage2.yml
CI still throwing errors related to ansible-lint
Fix no-changed-when error
Locally and in CI
None
> fix: ansible-lint no-changed-when

- lib/test/docker.js
- test/smoke/core.js
- test/smoke/drive.js
- test/smoke/quorum.js
- test/smoke/tenderdash.js
> fix(smoke): too high docker timeouts

- ansible/roles/elastic_beats/vars/platform.yml
Drive log output syntax changed between v0.24 and v0.25
Update Filebeat log ingest template
On devnet-absinthe
None
> chore: update logs syntax for drive 0.25

- ansible/reindex.yml
- ansible/roles/dashmate/tasks/reindex.yml
- ansible/roles/reindex_network/tasks/main.yml
- bin/reindex
https://github.com/dashpay/dash-network-deploy/issues/533
* Added reindex command
Devnet
No
> feat: add reindex binary

- ansible/roles/dashmate/tasks/build.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- lib/configGenerator/generateAnsibleConfig.js
New dashmate v0.24.19 released with some internal breaking changes
- Updated the dashmate config template 
- Do not change helper image to update dashmate
- Enable build flag for helper instead of running docker build command
None
None
> chore(dashmate): update to dashmate v0.24.19

- ansible/roles/dashd/templates/dash.conf.j2
EN registration was failing with `hpmn methods are deprecated`
Add support for deprecated RPC to dash.conf template so wallet node still works
On devnet-absinthe
None
> fix: hpmn methods are deprecated

- ansible/roles/dashmate/tasks/build.yml
- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
- lib/configGenerator/generateAnsibleConfig.js
- lib/test/wait.js
- package-lock.json
- package.json
- test/smoke/core.js
- test/smoke/quorum.js
- test/smoke_web/dapi.js
Numerous updates were needed to deploy using dashmate v0.25, and run tests against v0.25 networks
- pin wasm-bindgen version
- bump node version to 18
- handle zerossl logic error on first run when config is not yet set
- remove sentinel from dashmate config
- bump deps and version
- fix linter errors
On devnet-absinthe and devnet-ouzo
> chore: support Platform v0.25

- lib/configGenerator/generateAnsibleConfig.js
A variable was accidentally renamed to satisfy a linter, breaking use of the function output.
Revert var name change
Untested
None
> chore: revert var name to private_key

- test/smoke/dapi.js
Fixes failing `should return data from Platform` dapi test
Drive is not returning NOT_FOUND error with code 5 anymore, so we had to go with a different approach of checking the error
> test(dapi): fix data contract not found test

- .github/workflows/release.yml
- Dockerfile
Using the Docker image was failing due to Node version mismatches and other issues due to out-of-date packages.
Update all package, dependency and action versions
Locally
None
> chore: update docker release and deps

- ansible/roles/dashmate/tasks/main.yml
The name of the `dashmate config` task was not accurate, and it wasn't clear what running it was supposed to achieve
Use better name and add a comment
N/A
None
> docs: clarify the purpose of running `dashmate config`

- lib/configGenerator/generateAnsibleConfig.js
Generated config templates were missing some variables and setting old versions by default
- Add variables
- Update default values
Locally
None
> chore: update default versions in config and add vars

- test/smoke/dapi.js
- test/smoke_web/dapi.js
DAPI core smoke tests were failing on all evonodes with:
```
10) Smoke
DAPI
All nodes
hp-masternode-1
should return data from Core:
AssertionError: no block info
at Context.<anonymous> (test/smoke/dapi.js:92:20)
at process.processImmediate (node:internal/timers:476:21)
```
And smoke tests were failing with the same issue previously fixed in #550 
Fix test logic
Locally against testnet
None
> fix: AssertionError: no block info

- test/smoke/dapi.js
Invalid error handling for temporary broken DAPI )
- Do not check response to be undefined
Manually
None
> fix(tests): invalid DAPI error handling

- .github/workflows/test.yml
- lib/configGenerator/generateAnsibleConfig.js
Minor linting errors in config generator
- Enable ESLint in CI
- Fix linting errors
Locally
None
> chore: fix linting errors

- ansible/deploy.yml
- ansible/roles/mixing/tasks/main.yml
- ansible/roles/mn_protx_diff/tasks/main.yml
- ansible/roles/mn_status_report/tasks/main.yml
We were installing jq multiple times in different roles 
Install jq once only early in the deploy role
Untested
None
> chore: install jq once only

- ansible/roles/dashmate/templates/dashmate.json.j2
- lib/configGenerator/generateAnsibleConfig.js
https://github.com/dashpay/platform/pull/1468 adds the platform.drive.abci.epochTime setting to `dashmate.json`
Update templating to include this value
Locally
None
> chore: add drive abci epoch time to config

- ansible/roles/elastic_beats/tasks/main.yml
- ansible/roles/elastic_beats/vars/platform.yml
Revert changes to json-log as output is now in log files again rather than stdout
None
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added or updated relevant unit/integration/functional/e2e tests
- [x ] I have made corresponding changes to the documentation
> chore: push Drive logs from the file

- ansible/roles/dashmate/tasks/main.yml
Core containers were not updated when platform was destroyed, platform was updated and the older version of core was still running
Revise dashmate restart logic
On testnet
None
> fix: dashmate restart logic

- ansible/roles/elastic_beats/vars/platform.yml
Tenderdash now writes logs to the dashmate logs dir
Update filebeat template to read from dashmate logs dir
Untested
None
> chore: update filebeat platform template for tenderdash logs

- test/smoke/dapi.js
- test/smoke_web/dapi.js
Smoke tests expected `DataContract is not defned` for DAPI responses for platform checks. This bug was fixed in Platform v0.25.0 so smoke tests should be updated
- Expect error code 5 instead of buggy response
Manually
Some tests fro Platform < 0.25.0 will fail
> fix(test)!: wrong error expected

- package-lock.json
- package.json
bump version to 0.25.0-dev.8
bump version to 0.25.0-dev.8
N/A
N/A
> chore(release): bump version to 0.25.0-dev.8

- ansible/group_vars/all
- ansible/roles/elastic_stack/files/ilm_policy.json
- ansible/roles/elastic_stack/tasks/volume.yml
- terraform/aws/instances.tf
- terraform/aws/variables.tf
Our large EBS storage volumes were getting too expensive
Replace EBS storage with instance store
On `devnet-loggo`
Existing logs will be lost on deploy, and any change to logs servers other than restart will now result in data loss
> chore: use instance store for logs data

- ansible/roles/dashmate/templates/dashmate.json.j2
To ease troubleshooting of Drive issues we need more visibility on operations what we perform on the state
- Defined Drive ABCI logs in the new format https://github.com/dashpay/platform/pull/1487
- Added `groveDbOperationsFile` log
None
Supported Drive version >= 0.25.4
> feat!: add GroveDb operations log

- ansible/roles/dashmate/templates/dashmate.json.j2
Config schema validation error config format: Unexpected token
Fix invalid schema syntax
Untested
None
> fix: extra comma causing json schema validation error

- ansible/roles/elastic_stack/files/index-templates/logs-drive.tenderdash.json
We need to be able to search by `json.error` in Tenderdash logs
Enable full text indexing on `json.error` field
Untested
None
> chore: enable full text indexing on tenderdash errors

- ansible/deploy.yml
- ansible/roles/dash-conf/tasks/main.yml
- ansible/roles/dash-conf/templates/dash.conf.j2
Devs often need a minimal `dash.conf` file for a network. 
Implement a role to generate `dash.conf` for the network.
Locally
None
> feat: generate minimal dash.conf file in configs repo

- terraform/aws/instances.tf
- terraform/aws/variables.tf
We need more control over the type of instance used for logs nodes
Make logs node instance type a variable so it can be set from the network `.tfvars` file
On testnet
None
> chore: make logs node type a variable

- ansible/deploy.yml
Ensure seeds listen otherwise they will never sync, thus a devnet will never start.
> Fix: ensure seed listens

- ansible/roles/dashmate/tasks/main.yml
- ansible/roles/dashmate/templates/dashmate.json.j2
New dashmate version doesn't update config without changes made. Dashmate config has changed.
- Made some unnecessary change to force service configs rendering
- Added insight options to dashmate config template
Deploying testnet
None
> chore: update to new dashmate version

- terraform/aws/security_groups.tf
Add firewall rule for tenderdash 36660 from local network only for Prometheus
Testnet
None
> chore: add tenderdash firewall rule

- ansible/roles/dashmate/templates/dashmate.json.j2
The wrong variable was used in #605 to specify a private interface to listen connections from Prometheus
- Fixed to correct variable
None
None
> fix: invalid tenderdash metrics host

- ansible/group_vars/all
- ansible/roles/dashmate/templates/dashmate.json.j2
We need to temporary disable drive grovedb operation logs
- Added `drive_log_grovedb_operations` variable. Logs are disabled by default
None
Deployment with this PR will disable grovedb operation logs if you don't put `drive_log_grovedb_operations: true` to your network config
> feat: configure grovedb operation logs

- ansible/roles/dashmate/templates/dashmate.json.j2
> fix: object of type 'NoneType' has no len()

- ansible/group_vars/all
- ansible/roles/kill_logs/tasks/main.yml
- ES needed updating
- ES data wasn't deleted by destroy command
- Update to ES 8.11.3
- Ensure data volume is formatted by destroy command
On testnet
None
> chore: update es 8.11.3

- bin/ssh
You often SSH to different network's hosts to maintain/troubleshut or monitor network. Visiting inventory file every time is annoying
- Added `ssh` command to connect to the host by node name
Manually
None
> feat: ssh to host command
