dashpay/dash-network-deploy

cluster.yml, terraform/aws/inventory/ansible_inventory.tpl
Current ansible warning due to same group and host name:
```
[WARNING]: Found both group and host with same name: web
```
=> Fix ansible name conflict w/group and host

ansible/roles/multifaucet/templates/multifaucet/Dockerfile
Fixing of multifaucet is a wasting of time so we get rid of our fork and come back to tuaris's origin version https://github.com/tuaris/multifaucet
=> Use origin faucet instead of our fork

terraform/aws/instances.tf
to avoid error when region does not have t3 type instance introduced
=> change t3.nano to t2.nano for vpn

terraform/aws/instances.tf
This also removes the "unlimited" credit specification. Unlike `t2`s, `t3`s are
automatically set to unlimited credit usage by default.
=> Upgrade to t3 instance types from t2

terraform/aws/instances.tf, terraform/aws/main.tf, terraform/aws/security_groups.tf, terraform/aws/variables.tf
- adds a blacklist for AZs known to be not working
- renames the "private" subnets to public (they were always public because of
the default route table association w/a route to the internet)
- adds a list variable for subnet CIDR ranges
- use the different subnets instead of locating all instances into one single
AZ
=> Use multiple subnets for deploy

ansible/deploy.yml, ansible/group_vars/all, ansible/roles/swap/tasks/main.yml
Currently we are getting processes killed due to Out-of-Memory (OOM). Adding a swap file is standard to prevent this and can be used as a quick fix for OOM issues as well as to monitor for actual memory requirements (RAM) in case we want to bump those and provide a recommendation.
=> feat: add swap role and enable for all hosts

test/smoke_web/dapi.js
I wouldn't merge it before we fix that issue
=> test: dapi should respond with null via gRPC Web if data not found

terraform/aws/main.tf
Some of DNS services block records longer than 10 IPs
We add only 10 IPs to each DNS record.
With Terraform plan and with manually created DNS record with 10 IPs.
No
=> fix: some DNS services block long records

ansible/roles/mn-evo-services/templates/dapi-nginx-grpc.conf.j2
`grpc_pass` buffer size setting was to small resulting in `upstream sent too big header while reading response header from upstream` error
Increased buffer size to 128k
Local dev env.
=> fix: gRPC buffer size settings in NGINX was too small

ansible/roles/dashd/tasks/main.yml
Deprecated `getinfo` RPC command is removed in DashCore 0.16
Used `getblockchaininfo` instead of `getinfo`
With deploy
None
=> fix: `getinfo` RPC command is removed in DashCore 0.16

terraform/aws/main.tf
Updates provider syntax to v3
`terraform apply` fails with:
```
Error: Unsupported argument
on main.tf line 11, in data "aws_availability_zones" "available":
11:   blacklisted_names = ["us-west-2d"]
An argument named "blacklisted_names" is not expected here.
```
Update provider syntax as described here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#data-source-aws_availability_zones
Ran `dash-network deploy -i testnet`, no errors.
=> fix: use v3 AWS provider syntax

bin/dash-network, bin/generate, bin/generate-configs.js, lib/cli/init.sh
Checking for presence of the `.env` and loading its content was previously done in two places: in the `dash-network` command wrapper and in the `generate` command. This PR removes the duplicate code and moves the check into the init function.
This fixes the chicken/egg problem of not having an `.env` file and not being able to create one because `init.sh` checks for its existence first, and also the problem of overwriting existing `.env` files when running `generate`.
Remove `.env` forced exit in `dash-network` and check/generate in `init.sh` instead of in the generate command.
Tested running `bin/generate` from shell and `dash-network generate` with docker.
None
=> feat: validate .env in init

lib/cli/init.sh, lib/cli/terraform.sh, terraform/aws/main.tf
This PR fixes errors preventing DNS registration when using testnet config. Together with [this PR](https://github.com/dashevo/dash-network-configs/pull/38) to the config, it should resolve DNS errors for testnet.
Terraform was failing with:
```
data.template_file.ansible_inventory: Refreshing state...
Error: Invalid index
on main.tf line 136, in resource "aws_route53_record" "faucet":
136:   records = [aws_elb.web[0].dns_name]
|----------------
| aws_elb.web is empty tuple
The given key does not identify an element in this collection value.
Error: Invalid index
on main.tf line 147, in resource "aws_route53_record" "insight":
147:   records = [aws_elb.web[0].dns_name]
|----------------
| aws_elb.web is empty tuple
The given key does not identify an element in this collection value.
```
- …
=> fix: `main_domain` option doesn't work for testnet

test/smoke/core.js
Core chain name for devnet network consist devnet name as well so the current assert doesn't work for devnets
Compare chain name against `devnet-{name}`
Running tests
None
=> fix: wrong devnet chain name assert

ansible/roles/mn-fund-collateral/tasks/main.yml
Rescannig the blockchain is slow on testnet. This PR changes behaviour to import all owner keys, then rescan blockchain instead of rescanning after each key import.
Network deploy was too slow on testnet
Rescan blockchain after all keys are imported instead of rescanning after each key import.
Not tested
=> fix: rescan after all keys are imported

test/smoke/core.js, test/smoke/tendermint.js
Removed `dash_devnet_version` being used in smoke tests that lead network type assertion to be failed.
- Removed `dash_devnet_version` from Core network assertion
- Used `tenderdash_chain_id` in Tenderdash assertion
Running smoke tests
None
=> fix: removed `dash_devnet_version` being used in smoke tests

terraform/aws/main.tf
seed.*.networks.dash domain was marked as deprecated in v0.13 and should be removed
- remove deprecated CNAME record for seed
None
Deprecated seed.*.networks.dash domain is no longer available
=> chore!: remove deprecated CNAME record for seed

Dockerfile
Use recent pip version to avoid build errors during install
Build was erroring with `ModuleNotFoundError: No module named 'setuptools_rust'`
Add step to update pip version before installing requirements
Build completes successfully
=> fix: build error due to outdated pip

ansible/roles/dashd/templates/dash.conf.j2
llmq-qvvec-sync is used to synchronise quorum verification vectors
Masternodes not deployed by the deploy tool do not contain this setting
Add llmq-qvvec-sync=llmq_100_67 to dash.conf
Tested in #217 then moved here
=> feat: add llmq-qvvec-sync to dash.conf

ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
pBFT block time went ahead due to super frequent block processing and some functionality based on it doesn't work properly. To mitigate this problem we need temporarily slow down block production.
- Increased `timeout_commit` to `1s`
- Icreased `timeout_broadcast_tx_commit` to `30s` to support new `timeout_commit`.
- Incresad `create_empty_blocks_interval` to `10m`
- Set `keep-invalid-txs-in-cache` to `true` to do not produce blocks for invalid transactions that already were invalidated.
With deploy
None
=> fix: pBFT block time went ahead on testnet

ansible/roles/mn-evo-services/tasks/tendermint.yml
Tenderdash 0.34.4 deprecates underscore in commands.
- Replace underscore to dash in tenderdash commands
With deploy
Tenderdash < 0.34.4 doesn't supported
=> fix!: tenderdash commands with underscore are deprecated

terraform/aws/services_output.tf, terraform/aws/templates/services/services.tpl
This PR fixes a minor bug in the Terraform services template output
Terraform still outputs the web host address instead of the new logs host.
Modified output template to show correct information
Run against testnet config, output is good
None
=> fix: incorrect logs server address in services template

ansible/roles/eternal-terminal/tasks/main.yml
This PR changes the method ansible uses to add apt repositories to ensure that the signatures are added first (if missing).
ET deploy was failing with: `Failed to update apt cache: W:GPG error: http://ppa.launchpad.net/jgmath2000/et/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CB4ADEA5B72A07A1, E:The repository 'http://ppa.launchpad.net/jgmath2000/et/ubuntu bionic InRelease' is not signed.`
Modify use of `ansible.builtin.apt_repository` to ensure PPA keys are installed before trying to fetch packages from repo.
Tested by running on palinka. ET is now running on all palinka nodes.
None
=> fix: sigs missing while adding et apt repository

terraform/aws/main.tf
This PR fixes a bug to ensure the logs server is accessible through public DNS.
`logs.testnet.networks.dash.org` did not resolve in some browsers.
Changed record type from CNAME to A. Now I know the difference ;)
Tested locally, again with VPN enabled and again with https://cachecheck.opendns.com/
None
=> fix: logs address does not resolve in dns

ansible/group_vars/all, ansible/roles/elastic-stack/templates/docker-compose.yml.j2, terraform/aws/instances.tf, terraform/aws/variables.tf
This PR allows configuration of the instance size of the logs node.
Logs node was too slow and not configurable.
Specify defaults and add variables to configure AWS instance size and JVM heap size.
Tested on testnet
None
=> feat: make logs instance configurable

ansible/roles/dashd/templates/dash.conf.j2
Dash containers were failing with the following error after updating from `0.17.0.0-rc3` to `-rc4`:
```
Error: Invalid format in -llmq-qvvec-sync: llmq_100_67
```
Use new syntax for this setting
Tested on Palinka
None
=> fix: new llmq-qvvec-sync syntax in 0.17.0.0-rc4

ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Merk library is updated in Drive to a newer version. It uses the blake3 hashing algorithm that has 32 bytes hash size.
- Set `app_hash_size` to 32 bytes in Tenderdash config
Running a local network with dashmate
Drive with the previous version of Merk is not supported.
=> feat!: migrate Drive state tree to black3

Dockerfile
Building the Docker image was failing with:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 117: ordinal not in range(128)
```
This error is [caused](https://githubmemory.com/repo/pypa/pip/issues/10219) by a change in behavior of `pip 21.2.x`, which is incompatible with `Python 3.6.x`, which is near end of life.
- Updated base Linux distro to Ubuntu 20.04 (which updates `python3` to `3.8.x`)
- Updated Terraform, Node.js and Docker versions
- Tested build locally
- Tested running commands against testnet
None
=> chore: bump versions

.github/workflows/release.yml
Buildx v0.6.0 contains a [bug](https://github.com/docker/buildx/issues/703) that prevents variable substitution in docker compose files
Force installation of v0.6.1, which contains a fix
Tested working on `update-grpc` branch
None
=> ci: fix buildx var substitution in compose file

ansible/roles/mn-init/tasks/main.yml
Some masternodes became banned during a recent network upgrade. This exposed a bug in the `mn-init` role that caused the deploy tool to try and create new ProUpServTxs for every node in the inventory, not just the banned nodes.
Modify query to search list of banned nodes instead of the full list
On testnet
None
=> fix: mn-init unbans all nodes every time

bin/deploy
if the branch has devnet-* there will be a small check to make sure we're deploying the correct devnet. Note this won't apply to any existing branches (master, v22-dev, etc) and will only impact on branches with devnet-
This will ensure we don't accidentally deploy incorrect devnet configs over each other, devnet-specific configs will be stored in branches in Dash Network Deploy repo. 
There is also a new -f command which will force the deployment *anyway* - this is to be used if you're sure you want to deploy one devnet config over a different devnet.
Small change to bin/deploy which checks if we're in a devnet branch, then checks if we're in the *correct* devnet branch. This ensures we cannot overwrite devnet-krupnik with devnet-malort changes. (examples, it applies to all devnet-* …
=> feat: add devnet check

ansible/roles/elastic-beats/tasks/main.yml
If the `elastic-beats` role was deployed on a node without platform, filebeat would throw warnings that the services are not present
Only enable logging of platform services if platform is present
On testnet against miner and seed nodes
None
=> fix: platform logs not present filebeat error

bin/dash-network
Running smoke tests in CI from docker wrapped in the dash-network command resulted in the error `the input device is not a TTY`. It is not necessary to interact with the terminal when running smoke tests, so we should not keep STDIN open without being attached.
Remove interactive argument passed to `docker run`
In CI
None
=> fix: the input device is not a TTY

terraform/aws/versions.tf
We need to use a consistent major.minor version of terraform between devs and engineers using this tool
Bump required Terraform version to 1.1.8+
Tested locally against AWS with Terraform 1.1.8 and 1.1.9
Cannot use Terraform version older than 1.1.8
=> chore: bump terraform version to 1.1.8

ansible/roles/generate-blocks/tasks/main.yml, ansible/roles/mn-createprotx/tasks/main.yml, ansible/roles/mn-fund-collateral/tasks/main.yml, ansible/roles/mn-init/tasks/main.yml, ansible/roles/mn-protx-config/tasks/find-protx.yml, ansible/roles/mn-protx-config/tasks/main.yml, ansible/roles/mn-unban/tasks/main.yml
Running test suite against an arbitrary network in CI requires specification of the protx values in the new `MASTERNODE_REWARD_SHARES_OWNER_PRO_REG_TX_HASH` variable. We therefore need to add protx values for the registered masternodes to the inventory after they have been registered on the network, half way through the deploy process.
- Fix warnings about deprecated Ansible `include` statement in all files
- Add a new task in the `mn-init` role to write the protx values to the inventory file when known
Locally against valhalla and testnet
Preview output is here: https://github.com/dashevo/dash-network-configs/pull/66
=> feat: write protx values to config inventory file

ansible/roles/generate-blocks/tasks/regtest_generate.yml, ansible/roles/generate-firstblock/tasks/main.yml
`dash-cli generate` returns `error message: Method not found` with 18.1.x builds of Dash Core
Replace `generate` with `generatetoaddress`, this command is backwards compatible so older versions of core should still work when runnings tasks that require blocks to be created.
Tested while deploying a devnet with the latest core build on `devnet-jammy`, a small devnet to test updating the Ubuntu base image.
None
=> fix: generate command not found with core 18.1.0

ansible/deploy.yml
Devs want to be able to connect to the remote docker context, but the ssh key is associated with the `ubuntu` user account which is not in the `docker` group.
- Add `ubuntu` user to the `docker` group
On `devnet-sangsom` with Djavid
None
=> fix: cannot attach to docker context with ubuntu key

ansible/deploy.yml, ansible/group_vars/all, ansible/roles/ecr-login/tasks/main.yml, lib/cli/init.sh
We don't use ECR any more and this removes an unnecessary role.
=> chore: Remove unused ecr_login role

ansible/group_vars/all, ansible/roles/dash-cli/tasks/main.yml, ansible/roles/dashd/tasks/main.yml, lib/configGenerator/generateAnsibleConfig.js
This consolidates the 2 variables `dashd_evo_image` and `dashd_image`. There is no need for both of them, since they are both refer to the same service.
=> chore: Remove dashd_evo_image (use dashd_image)

package-lock.json, package.json, test/smoke/core.js
Smoke tests were timing out without returning errors
- Move collect blockchaininfo call from before function to separate test
- Refactor blockchaininfo call to timeout on individual node failure
Locally and in [CI running against test build here](https://github.com/dashevo/dash-network-ci/runs/6922072178?check_suite_focus=true)
None
=> perf: speedup core smoke test

ansible/roles/dashd/tasks/main.yml
The `getblockchaininfo` call is heavy, consumes a lot of resources. Since we are only using this to check if RPC is ready, we can use something light like `getgovernanceinfo` instead. This saves 2-3 seconds each time it's called.
Changed `getblockchaininfo` to `getgovernanceinfo` in dashd RPC check.
I tested this by running the dashd play on a testnet masternode, once.
n/a
=> fix: Use getgovernanceinfo in RPC check

ansible/roles/dashd/tasks/main.yml
The Dash user plays are excessive and can be reduced to 1 play using user module.
- Shell outs not required for uid/gid, this is in the user module register.
- The home dir creation can be done in the user module too.
- The append is not useful here, since it defaults to false and no groups are listed anyway.
- It is helpful to add a user name comment
- Removed shell calls to id command.
- Make user module create home dir.
- Remove unused append argument.
- Add a user name comment
Ran on testnet masternode
n/a
=> refactor: reduce dash user complexity

ansible/roles/mn-sentinel/templates/docker-compose.yml
This just tidies the Sentinel docker-compose file a bit and enables debug logging.
The NETWORK variable is no longer used.
- Remove NETWORK env var
- Enable debug logging by setting SENTINEL_DEBUG
- Use long form of `--bypass-scheduler` option to reduce confusion.
I have tested this on several testnet MNs by running the mn-sentinel role
n/a
=> chore: tidy sentinel docker-compose, enable debug

ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2
Tenderdash 0.8 was crashing with `ERROR: While parsing config: (57, 8): no value can start with v`
Quote value
None
=> fix: no value can start with v

package-lock.json, package.json
Use of dashd-rpc 2.4.0 was causing smoke tests to throw errors related to timeouts. dashd-rpc 2.4.1 fixes this.
Update to dashd-rpc 2.4.1
Locally against testnet
None
=> chore: bump dashd-rpc to 2.4.1

ansible/group_vars/all, ansible/roles/dashd/tasks/main.yml
User dashcore directories are not consistent among the 3 users that we have on MNs.
Adds a loop to create .dashcore directory for root, dash and ubuntu users.
Tested on some testnet masternodes using dashd role.
n/a
=> chore: Create dashcore dir for each user in a loop

ansible/roles/dashd/tasks/main.yml
The dash.conf file is copied around for different users for dash-cli ease of use, but it's easy to get divergent (differences in the file).
This PR adds the file in one single location (`/etc/dash.conf`) and then symlinks it into user directories so that dash-cli can be called easier by any of the users.
Needs #313 first.
Tested on some testnet masternodes using dashd role.
n/a
=> chore: Consolidate dash.conf in one place and symlink

ansible/roles/dashd/defaults/main.yml, ansible/roles/dashd/tasks/main.yml, ansible/roles/dashd/templates/.env.j2, ansible/roles/dashd/templates/docker-compose.yml.j2
Currently dashcore must be managed only via the Ansible play. This will allow management of the dashcore container locally,  and give the ability to locally tweak the config (image, command, etc) via the docker-compose.yml file. This is (I believe) the only service we run that does not use docker-compose in the tool.
Adds a docker-compose.yml file for dashcore, and uses docker-compose to manage the container. Also removes the play which users docker container to manage it.
Tested on masternode on testnet.
n/a
=> feat: Write and use docker-compose file for dashcore

ansible/roles/mn-evo-services/tasks/tendermint.yml, ansible/roles/mn-evo-services/templates/tendermint/config.toml.j2, ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
Tenderdash since version 0.36 is using boostrap peers to connect to the network. Also new version of tenderdash expect default values for validators set and quotum hash in genesis file.
- Fixed genesis.json and config.toml generation
None
The new config won't be compatible with previous versions of tenderdash
=> fix: outdated tenderdash configs

ansible/roles/dashd/tasks/main.yml
The `getblockchaininfo` call is too heavy to be used as an RPC check.
Backport rpc check change (#310) into master. This is already in v0.23-dev but we need it today in master for testnet.
Tested on all masternodes and seed nodes on testnet.
n/a
=> fix: Use getgovinfo in RPC check

ansible/deploy.yml, ansible/roles/elastic-beats/tasks/main.yml, ansible/roles/elastic-beats/vars/common.yml, ansible/roles/elastic-beats/vars/core.yml, ansible/roles/elastic-beats/vars/platform.yml
During recent core testing, it was common to recreate the core container without replaying the remainder of the playbook. Because `elastic-beats` was only set to run for platform deployment, this means that core logs were no longer captured if the platform deployment did not run.
This PR adds `elastic-beats` to core plays on all nodes, including miner, wallet and web nodes for the first time. Running core plays will now also update filebeat with new container IDs, and platform config is conditionally deployed on each run of the play, depending on whether platform is deployed or not.
- On devnet-jack-daniels
@nmarley is this still idempotent? I'm not quite sure how to reason about deploying a single config to cover all three services at different times in the playbook.
**For repository …
=> feat: conditional core/platform elastic beats

ansible/roles/elastic-stack/tasks/main.yml, ansible/roles/openvpn/tasks/main.yml
For elastic-beats and vpn roles it will use the generic /tmp directory, this is an issue as these files are then "locked" by that user. In the case of using a manager node with multiple users the other users will then get "permission denied" when they attempt to do a deployment
elastic-beats and vpn roles now use local directory in the user's home to generate certificates
Deployed a devnet
If another user deploys over the top, it will regenerate a certificates. This shouldn't be too much of an issue AFAIK
=> fix: use local directory in case of multiple users

test/smoke/drive.js
Drive tests were failing against devnet-jack-daniels
Update old magic string to new magic string provided by shumkov
Won't work with Drive <0.23
=> fix: drive tests fail against v0.23

lib/test/bootstrap.js, lib/test/openVpn.js
OpenVPN remains connected after interrupting a smoke test run with Ctrl + C. Subsequent runs reuse the same VPN connection, meaning it is not possible to run smoke tests on a different network without first running `sudo kill $(pidof openvpn)`.
Catch `SIGINT` and give OpenVPN time to disconnect and destroy the client.
On `devnet-jack-daniels`
This changes the prior behaviour, but I consider it a fix of incorrect behaviour rather than a breaking change of behaviour
=> fix: openvpn persists after SIGINT

ansible/roles/openvpn/tasks/main.yml
OpenVPN routes were being parsed incorrectly as strings instead of a list in Ansible, resulting in an OpenVPN conf file on the VPN node which appeared as below. These bad routes were then passed to the connecting node, resulting in failures when running smoke tests.
```
push "["
push " "
push "'"
push "r"
push "o"
push "u"
push "t"
push "e"
push " "
push "5"
push "2"
push "."
push "3"
push "9"
push "."
push "6"
push "1"
push "."
push "3"
push "7"
push " "
push "2"
push "5"
push "5"
push "."
push "2"
push "5"
push "5"
push "."
push "2"
push "5"
push "5"
push "."
push "2"
push "5"
push "5"
push "'"
push " "
push "]"
```
Fix ansible syntax, thanks @kxcd for generous help tracking this down
On testnet
None
=> fix: vpn not adding routes correctly

ansible/requirements.yml, ansible/roles/dashd/defaults/main.yml
```
[DEPRECATION WARNING]: Use 'ansible.utils.ipsubnet' module instead. This feature will be 
removed from ansible.netcommon in a release after 2024-01-01. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
```
- Fix YML file syntax
- Add ansible.utils dependency and declare this namespace where used in roles
On `devnet-filebeat`
None
=> fix: ansible.netcommon deprecation

ansible/roles/mn-evo-services/tasks/main.yml
Platform logs were not being rotated hourly because the version of logrotate shipping with ubuntu [disables](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858021) running from cron if systemd is installed.
Specify hourly logrotate using systemd
On devnet-filebeat
None
=> fix: platform logs not rotated hourly

ansible/roles/dashd/tasks/main.yml
logrotate 3.11.x, which is installed on Ubuntu 18.04, does not create systemd timers in the same way as the version shipped by 22.04
Use cron to trigger logrotate hourly
We have already been using this approach in mn-evo-services
None
=> fix: logrotate doesn't use systemd on ubuntu bionic

lib/cli/test.sh
Smoke tests in CI were completing with green status if karma tests completed green, even if errors occurred in the mocha test run ([example](https://github.com/dashevo/dash-network-ci/actions/runs/3102113878/jobs/5024115496)). We need to run both mocha and karma tests each time, but exit with an error code if either tool exits with an error code.
Replace incomplete `set` logic with `trap`
Against testnet
None
=> tests: green tests after errors in mocha

ansible/deploy.yml, ansible/roles/mn-init/tasks/main.yml
Terraform frequently overwrites the inventory file, making it necessary to run the `mn-protx-config` role again. This was previously part of `mn-init`, meaning three files needed commenting to run just this role.
Move role out to separate step so it can be run separately with greater ease
None
=> chore: move inventory update to separate step

README.md
The initial setup for AWS accounts is not documented and errors are returned from the tool if these steps aren't run.
Add some initial steps to the README for brand-new, fresh AWS accounts trying to deploy dash networks.
Tested on a call w/incubator dev @pshenmic .
n/a
=> docs: add initial AWS account setup to README

README.md
This purely cosmetic change to the README reflects the modern name we are using for the Dash Platform.
Rename Evolution to Platform in the README
=> docs: rename Evolution to Platform in README

ansible/roles/elastic-stack/tasks/main.yml
It was not possible to re-deploy a network of the same name from the manager node if different users were doing the second deploy because the temp dir for storing certs was not writable by the other user.
Ensure temp dir is writable by all users
Untested, but this should totally work 🙈
None
=> fix: permission denied reading file on shared manager node

ansible/roles/mn-evo-services/templates/tendermint/genesis.json.j2
Quorum hash should be set to hex 32 bytes null.
Update `quorum_hash` initial value in `genesis.json`. 
On `devnet-jack-daniels`
None
=> fix: quorum hash value

ansible/roles/elastic-stack/tasks/main.yml
Use local tmp dir for elastic otherwise permissions are not correct if more than two users run dash-network-deploy on one box.
Used homedir instead of /tmp
Deployed devnet-infratest
None
=> Use local tmp dir for elastic

ansible/roles/openvpn/tasks/main.yml
OpenVPN DH params were [generated by a role dependency](https://github.com/kyl191/ansible-role-openvpn/blob/master/tasks/server_keys.yml#L88-L105) fresh for each devnet, a process which takes around 4-5 minutes on each deployment. This is not necessary, params are not secret and the slight theoretical advantage they give an attacker is not relevant here because our devnets are low value targets.
Enable `openvpn_use_pregenerated_dh_params` setting
In a deployment
None
=> chore: enable use_pregenerated_dh_params

ansible/roles/dashd/templates/dash.conf.j2
Ody requested to be able to individually toggle MN debug logs so it is not all/nothing.
This solution looks for masternode.debug or the global dashd_debug variables. It uses defined for masternode.debug so previously generated configs will work just fine
Now we can simply add this sample code to MN's that need debug logs on:
`masternodes:
masternode-1:
owner:
address: xx
private_key: xx
collateral:
address: xx
private_key: xx
operator:
public_key: >-
xx
private_key: xx
node_key:
id: xx
private_key: >-
xx
**debug: 1**`
devnet
None, backwards compatible AFAIK.
=> feat: individual MN debug toggle

bin/deploy
`bin/deploy` would fail with exit code 1 and no visible error if deploying from a commit below HEAD on any given branch
Remove `-q` so the failing command displays an error, thusly:
```
Deploying devnet-jack-daniels network...
fatal: ref HEAD is not a symbolic ref
```
Locally
=> fix: deploy fails silently if current branch not at HEAD

ansible/roles/mn_evo_services/tasks/main.yml
This command was refactored to use the `docker_compose` module, which had the unintentional side effect of starting the services as well as pulling them. Since we no need to run `tenderdash init` before starting tenderdash, we no longer need to pull the images before starting the services, which happens at the end of this role.
Remove explicit pull command when setting up platform
None
=> fix: double platform service startup

ansible/roles/elastic_beats/tasks/main.yml, ansible/roles/elastic_beats/vars/core.yml, ansible/roles/elastic_beats/vars/platform.yml
`elastic_beats` was collecting container IDs through a shell command rather than an ansible module.
Switch to using ansible module
On custom devnet
None
=> chore: use module instead of command to list docker containers

ansible/roles/mn_createprotx/tasks/createprovidertx.yml, ansible/roles/mn_createprotx/tasks/main.yml, ansible/roles/mn_unban/tasks/createproupservtx.yml
Collaterals are consumed as fees when creating protx transactions using a named wallet in Core 18
Work around the issue by funding a separate fee address
Currently testing on `devnet-feefix`
=> fix: collaterals being spent when creating protx

ansible/roles/multifaucet/tasks/main.yml
Most networks use `dashpay/multifaucet:latest` as the default faucet image. Since this tag can point to different images over time, the role must pull the image to leave the target in the desired updated state. To override this, specify a semver tag instead.
Update faucet image if necessary when running multifaucet role.
On testnet
None
=> chore: role should leave faucet in updated state

ansible/roles/dashd/tasks/main.yml, ansible/roles/mn_createprotx/tasks/createprovidertx.yml, ansible/roles/mn_createprotx/tasks/main.yml, ansible/roles/mn_init/tasks/main.yml, ansible/roles/mn_protx_config/tasks/main.yml, ansible/roles/mn_unban/tasks/createproupservtx.yml, ansible/roles/mn_unban/tasks/main.yml
Supersedes #405 and #406 
#390 introduced use of the `loadwallet` command, which fails to lock masternode outputs present in the wallet on load. Deploy tool depends on these outputs being locked, so the issue results in masternode collaterals being consumed as fees in other transactions. This issue was handled with static fee addresses in #400, which introduced a new limitation on how many transactions the deploy tool could create without needing to wait for a block. We need to revert code from these two PRs and load both wallets on startup to ensure outputs are locked.
Revert #400 
Partially revert #390 
Introduce handling for misconfigured masternodes (ENABLED but with wrong service address, and cannot be banned because all nodes have wrong service address)
On `testnet` and …
=> chore: fix loadwallet and handle misconfigured masternodes

ansible/roles/mn_evo_services/templates/tendermint/genesis.json.j2
Supersedes #368 
`genesis.json` can be reduced as much of the config is supplied by drive
remove/rename fields as necessary
On `devnet-bintang`
Doesn't work with tenderdash < `0.10.0-dev.6`
=> refactor: use reduced genesis.json template for tenderdash 0.10.0-dev.6+

ansible/roles/elastic_stack/tasks/configure_cluster.yml
The Elasticsearch `/_cluster/health` endpoint was returning `yellow` status due to missing replicas, even on networks where only a single logging node is present and replicas are therefore not possible. This was causing smoke tests to fail and turn red. We don't like yellow or red; green is our favourite colour.
Set `number_of_replicas: 0` if logging cluster size is 1.
On `devnet-bintang`
None
=> fix: elasticsearch cluster status yellow due to missing replicas

ansible/roles/dashd/templates/dash.conf.j2
A newline character was missing after templating, resulting in `debug=1uacomment=dcg-masternode-1`
Jinja has changed rules around newline whitespacing recently. Easiest fix is to add a hard, untemplated newline to ensure it works on all versions.
On testnet
None
=> fix: uacomment spacing

ansible/deploy.yml, ansible/group_vars/all, ansible/roles/mn_find_collateral/scripts/find-collateral.py, ansible/roles/mn_fund_collateral/tasks/fund_collateral.yml, ansible/roles/mn_fund_collateral/tasks/main.yml, ansible/roles/mn_init/tasks/main.yml
Most apps deal with dash not duffs and dividing duff amounts in Python causes type casting problems. Jinja2 templating always returns a string, which makes further handling of output from the conditional logic extremely annoying.
Remove jinja2 template and simplify logic, replace division with multiplication
On `devnet-xxxx`
None
=> fix: confusing division and type casting

ansible/roles/mn_fund_collateral/tasks/main.yml
All masternodes (not just those with missing collateral) were funded when `not collateral_all_ok`, resulting in lots of additional collaterals if one mn collateral was bad for any reason (spent, not funded, mn added, etc.)
Check status of each masternodes collateral before adding to the list of funding targets
On `devnet-xxxx`
None
=> fix: all mns are funded collateral if only one is not ok

ansible/roles/dashd/tasks/main.yml
Fixes the import wallet issue on redeployment by moving the import above starting (so it is already there when we start)
If there is no wallet, it will *not* add to the configs. However it will then create (and import) the wallets on first loadup. 
There is a small issue where if we restart the wallet node *after* first deployment, but have not done subsequent deployments, the wallet won't be there. This is minor, and can be fixed by simply loading the wallet, I do not expect this to come up very often (mostly for failed deployments where we do a manual restart)
devnet-infratesting
=> fix: move import wallet and check

ansible/roles/aws/tasks/main.yml, ansible/roles/dash_cli/tasks/main.yml, ansible/roles/dashd/tasks/main.yml, ansible/roles/dashd_generate_miner/tasks/main.yml, ansible/roles/docker_options/tasks/main.yml, ansible/roles/elastic_stack/tasks/generate_certs.yml, ansible/roles/elastic_stack/tasks/main.yml, ansible/roles/elastic_stack/tasks/volume.yml, ansible/roles/insight/tasks/main.yml, ansible/roles/mn_evo_services/tasks/main.yml, ansible/roles/mn_evo_services/tasks/tendermint.yml, ansible/roles/mn_find_collateral/tasks/main.yml, ansible/roles/mn_sentinel/tasks/main.yml, ansible/roles/mn_status_report/tasks/main.yml, ansible/roles/multifaucet/tasks/main.yml, ansible/roles/openvpn/tasks/main.yml, ansible/roles/swap/tasks/main.yml, ansible/roles/tcpdumpd/tasks/main.yml
Our linting package will update soon, causing error `yaml[octal-values]: Forbidden implicit octal value "0644"` due to changes in the way the yaml standard handles octals.
Quote octal values as required in current ansible-lint documentation: https://ansible-lint.readthedocs.io/rules/yaml/#octals
With ansible-lint 6.13.1
None
=> chore: update yaml octal quoting required in ansible-lint 6.13.1

ansible/group_vars/all, terraform/aws/security_groups.tf, terraform/aws/services_output.tf, terraform/aws/variables.tf
DAPI no longer uses separate ports for HTTP and GRPC, it is all on port 3000
Remove references to dapi_grpc port 3010
Untested
None, hopefully - we will find out while deploying v0.24 builds in coming weeks
=> chore: remove dapi-grpc port

terraform/aws/main.tf
On a network with 12 HPMN and 0 MN:
```
│ Error: creating Route 53 Record: InvalidInput: Invalid request: Expected exactly one of [AliasTarget, all of [TTL, and ResourceRecords], or TrafficPolicyInstanceId], but found none in Change with [Action=CREATE, Name=seed-3.paulaner.networks.dash.org, Type=A, SetIdentifier=null]
│       status code: 400, request id: 08b8712d-d459-40e5-a5fb-04ec3ac404c7
│ 
│   with aws_route53_record.masternodes[2],
│   on main.tf line 244, in resource "aws_route53_record" "masternodes":
│  244: resource "aws_route53_record" "masternodes" {
│ 
╵
```
Allow public IP selection from HPMN as well as MN when shuffling IPs to use as seeds
On devnet-paulaner
None
=> fix: route 53 no resources found on network with 0 masternodes

ansible/destroy.yml
When destroying platform we need to target HPMN not MN
Change platform destroy inventory target to `hp_masternodes`
On `devnet-paulaner`
None
=> chore: destroy platform on hpmn instead of mn

ansible/roles/dashmate/templates/dashmate.json.j2
Platform PR [#869](https://github.com/dashpay/platform/pull/869) changed the syntax of `config/platform/dapi/envoy/ssl/provider` from `selfSigned` to `self-signed`, resulting in the following error on `yarn dashmate start`:
```
stderr: |2-
InvalidConfigFileFormatError: Invalid
'/home/dashmate/.dashmate/config.json' config format:
config/platform/dapi/envoy/ssl/provider must be equal to one of the
allowed values
```
Update template to use `self-signed`
On `devnet-sam-adams` while testing #458
None
=> fix: ssl/provider must be equal to one of the allowed values

test/smoke/quorum.js
IS tests would time out on testnet with:
```
AssertionError: expected 'false' to equal 'true'
+ expected - actual
-false
+true
at Context.<anonymous> (test/smoke/quorum.js:261:76)
at processImmediate (node:internal/timers:466:21)
```
on around half the nodes.
Increase wait time before checking for instantsend lock on the transaction
=> fix: is lock smoke test expected 'false' to equal 'true'

ansible/roles/dashmate/tasks/delete_files.yml, ansible/roles/dashmate/tasks/main.yml, ansible/roles/dashmate/tasks/reset_platform.yml, ansible/roles/dashmate/tasks/set_vars.yml
#479 implementation doesn't cover platform destroy logic
- Added the dashmate package support to the platform destroy tasks
None
None
=> fix: destroy platform tasks doesn't support the installation from package

terraform/aws/instances.tf
Issue described in PR https://github.com/dashpay/dash-network-deploy/pull/481 - this is a better fix than ignoring lifecycle changes and supersedes that PR
Always set associate public IP to true even if we are going to later replace with an EIP. Terraform does not track state changes correctly here (breaking standards with AWS CloudFormation which does but I digress...)
Terraform has a few long standing issues about this: 
https://github.com/hashicorp/terraform-provider-aws/issues/343
https://github.com/hashicorp/terraform/issues/9811
Devnet
Possibly previous networks with HPMNs may need to redeploy.
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added or updated relevant …
=> fix: always set associated IP to be true

lib/configGenerator/generateTerraformConfig.js
EIPs should only be enabled on testnet or when specified, but configs were generated such that the default `true` value was applied
Generate `create_eips: false` in terraform config
On devnet-absinthe
None
=> fix: devnets are incorrectly generated with eips enabled

terraform/aws/main.tf
`seed-n.network.networks.dash.org` nodes incorrectly included masternodes. The nodes in these DNS entries are intended to be accessed through DNS names for DAPI endpoints only.
Remove masternodes from random shuffle ips
On testnet
Nones
=> chore: ensure seeders only return HPMNs

terraform/aws/main.tf
Fix for InvalidInput error when creating a new devnet without EIPs
```
│ Error: creating Route 53 Record: InvalidInput: Invalid request: Expected exactly one of [AliasTarget, all of [TTL, and ResourceRecords], or TrafficPolicyInstanceId], but found none in Change with [Action=CREATE, Name=seed-5.kazan.rd.dash.org, Type=A, SetIdentifier=null]
│       status code: 400, request id: 698eefac-42b8-4544-a40b-647191f56c42
│ 
│   with aws_route53_record.masternodes[4],
│   on main.tf line 259, in resource "aws_route53_record" "masternodes":
│  259: resource "aws_route53_record" "masternodes" {
│
```
We are currently sending blank DNS records if EIPs are disabled, this PR changes it to use the public_ip as fallback if there are no EIPs on the network. 
devnet-lol
None
**For repository code-owners …
=> fix(terraform): InvalidInput error

terraform/aws/main.tf, terraform/aws/security_groups.tf, test/smoke/dapi.js
The feature here is the creation and configuration of an AWS Elastic Load Balancer (ELB), ACM Certificate, Route53 Record and Security Group using Terraform. This setup is required to make seed-*.testnet.networks.dash.org accessible over HTTPS since the old method will not work while DAPI has differing certificates.
New ELB for seeds with the correct certificates, adding HPMNs as backends on port 3001. 
devnet-dude
N/A
=> feat: ELB & certs for seed addresses

ansible/roles/dashmate/templates/dashmate.json.j2
Default value for dashmate_platform_dapi_envoy_ssl_provider_config_zerossl_api_key is `null` and check fails for nodes without this property set.
Fixed check condition
On the devnet
None
=> fix: zerossl condition check

ansible/deploy.yml, ansible/group_vars/all
It's impossible to change correctly path dashmate logs, since the deploy playbook is using a hardcoded path.
- Define a variable on playbook level and use it in the playbook
None
None
=> fix: hardcoded path to dashmate logs

ansible/roles/dashmate/tasks/destroy_platform.yml, ansible/roles/kill_platform/tasks/main.yml
Destory platform doesn't remove SSL certificates and otherelated files
- Use the `--hard` flag to remove files as well
Destorying the platform
None
=> fix: destroy platform keeps config files

ansible/roles/dashmate/tasks/main.yml
If deploy tool was run for a second time after dashmate had started, and then dashmate was restarted, core would fail to start with error `Error: Could not open debug log file /var/log/dash/core.log`
Don't recursively set permissions on directory contents
On testnet
None
=> fix: core debug log permissions

ansible/roles/dashmate/tasks/ssl/self_signed.yml, ansible/roles/dashmate/tasks/ssl/zerossl.yml
When deploying Zerossl on evonodes for the first time, error: `msg: Destination directory /home/dashmate/.dashmate/ssl/testnet does not exist`
Ensure directory exists
On testnet 
None
=> fix: ssl dir missing for zerossl

terraform/aws/main.tf
Rust DAPI client requires HTTP2 for testing
Related PR: https://github.com/dashpay/platform/pull/1182
Enable HTTP2 on NLB
On testnet
None
=> feat: enable HTTP2 on NLB

ansible/roles/dashmate/tasks/main.yml, ansible/roles/dashmate/tasks/ssl/zerossl.yml, ansible/roles/dashmate/templates/dashmate.json.j2
Every time the dashmate role runs on an evonode, it causes the entire stack to restart because of a perceived change in the config file, when in fact it was the value of `platform.dapi.envoy.ssl.providerConfigs.zerossl.id` would flap between the value of `null` rendered by the `config.json` template, and the actual value rendered by the zerossl subrole.
```
TASK [dashmate : Write dashmate config file] *****************************************
--- before: /home/dashmate/.dashmate/config.json
+++ after: /home/strophy/.ansible/tmp/ansible-local-86335kydorlzs/tmpq87_w11n/dashmate.json.j2
@@ -112,7 +112,7 @@
"providerConfigs": {
"zerossl": {
"apiKey": "f5389f3dc2074934081cf6b319552993",
-                  "id": "f0c91347940e73f1809f85c720231364"
+                  "id": null
}
}
}
```
- Get …
=> fix: dashmate config changed on every run

ansible/roles/mn_init/tasks/main.yml
Waiting for a rescan of the entire wallet each time nodes needed unbanning was tedious and usually unnecessary in the first place.
We now check if the addresses we are about to import are already imported before importing them. This still takes the amount of time needed to `mn_count * 2` RPC commands, but we can skip the subsequent rescan step, saving a bit of time on testnet unban procedures.
On testnet 
None
=> chore: speedup address import

ansible/roles/dashmate/templates/dashmate.json.j2
Drive v0.25 is starting the chain on Core v20 activation. The initial core chain locked height option is still supported overriding the behavior. 
- Render `initail_core_chain_locked_height` only if set
None
None
=> feat(dashmate): optional initial core chain locked height

ansible/roles/dashmate/tasks/ssl/zerossl.yml, ansible/roles/kill_platform/tasks/main.yml
Minor errors occurred during first full deploy after merging zerossl changes
Fix incorrectly named vars
On testnet
None
=> fix: misnamed vars

ansible/roles/dashmate/tasks/build.yml, ansible/roles/dashmate/tasks/main.yml
This reverts commit 77f0b50fa9ddfd9997108dcf98dbb595ab31f9b9.
`stat`ing for the file incorrectly assumed that just because the file exists, that it would contain a configred default config, or be valid syntax for the current version of dashmate
Replace `stat` with `dashmate config`, which will error if:
- File is missing
- default config is not set
- file is invalid
On testnet
None
=> chore: revert replace dashmate config command with config file stat

ansible/roles/dashmate/templates/dashmate.json.j2
We were checking `initial_core_chain_locked_height` instead of `platform_initial_core_chain_locked_height` when conditionally templating the start height into `genesis.json`
Check `platform_initial_core_chain_locked_height` since we use this prefix for the var in deploy tool config
On testnet
None
=> fix: initial_core_chain_locked_height missing even if defined

ansible/group_vars/all, ansible/roles/dashd/defaults/main.yml, ansible/roles/dashd/templates/dash.conf.j2
`isseednode` no longer served any purpose, because seed nodes are configured by dashmate. Additionally, all non-seed nodes were pointing at the same seed node (always `seed-1`). 
- Remove `isseednode`
- Target seed nodes evenly when templating dash.conf
On testnet
None
=> refactor: remove `isseednode`

test/smoke/drive.js
Drive smoke tests were failing on all nodes with:
```
1) Smoke
Drive
HP masternodes
"before all" hook: Collect echo info from Drive in "HP masternodes":
Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/strophy/Code/dashpay/dash-network-deploy/test/smoke/index.spec.js)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
```
I noticed that the Tenderdash tests run the exact same command, but were not failing as a whole. Adjusting the timeout to match the value in the Tenderdash tests resolves the issue for me. I don't know why this works, but it does.
Against testnet
None
=> fix: Error: Timeout of 20000ms exceeded

ansible/roles/dashmate/tasks/main.yml, ansible/roles/dashmate/tasks/ssl/zerossl.yml, ansible/roles/dashmate/templates/dashmate.json.j2
During deploy, if certificate was changed in dashmate config, instead of updating SSM we rewrite config back to old value from SSM. It prevents dashmate helper to update certificates automatically.
- Write ID from SSM to config only if the value in config is null. We do not overwrite new certificate, created with the dashmate helper or the obtain command.
- Update SSM when ID from config and SSM are different. It means certificate was updated with the dashmate helper or the obtain command.
None
None
=> fix(dashmate): switch back to outdated certificate on deploy

ansible/deploy.yml, ansible/group_vars/all, ansible/roles/dashmate/tasks/main.yml, ansible/roles/dashmate/templates/dashmate.json.j2, ansible/roles/elastic_beats/tasks/main.yml, ansible/roles/elastic_beats/vars/core.yml, ansible/roles/elastic_beats/vars/platform.yml, ansible/roles/kill_platform/tasks/main.yml, ansible/roles/tenderdash/defaults/main.yml, ansible/roles/tenderdash/tasks/main.yml, ansible/roles/tenderdash/templates/.env.j2, ansible/roles/tenderdash/templates/docker-compose.yml.j2, ansible/roles/tenderdash/templates/tenderdash/config.toml.j2, ansible/roles/tenderdash/templates/tenderdash/genesis.json.j2, ansible/roles/tenderdash/templates/tenderdash/node_key.json.j2, terraform/aws/instances.tf, test/smoke/core.js, test/smoke/quorum.js
Seed nodes should no longer be deployed by dashmate
Implement Tenderdash-only role in deploy tool
On testnet seed-3
None
=> chore: create tenderdash role for seed nodes

ansible/deploy.yml, ansible/requirements.yml
We have been using the Cloudwatch monitoring scripts written in Perl to send data from instances to Cloudwatch. These scripts seem to have been deprecated sometime in 2020, and should be replaced with Cloudwatch Agent.
Replace unmaintained `aws-scripts-mon` Ansible role with maintained `christiangda.amazon_cloudwatch_agent`.
Tested on testnet `masternode-1`
crontab for `ubuntu` user needs to be cleared and the `/opt/aws-scripts-mon` directory deleted on all nodes to avoid delivering metrics twice. I'll take this step when merging the PR, after verifying metrics are being delivered properly.
=> chore: replace cloudwatch mon script with cloudwatch agent

ansible/roles/elastic_beats/tasks/main.yml, ansible/roles/elastic_beats/vars/drive.yml, ansible/roles/elastic_beats/vars/platform.yml, ansible/roles/elastic_beats/vars/tenderdash.yml
Filebeat needs to support the following new configs:
- Reading drive logs from `drive-json.log` on dashmate-managed evonodes
- Reading tenderdash logs from both evonodes and seed nodes
- Split platform logs rules into separate files and update template merge logic
- Read tenderdash logs from Docker because `tenderdash.log` is not available on seed nodes
On testnet hp-masternode-10
None
=> chore: update filebeat templates to support drive from file and tenderdash only on logs nodes

terraform/aws/monitoring.tf, terraform/aws/variables.tf
We want to be able to selectively enable CloudWatch alarms in order to control costs.
Make monitoring config granular, so we can enable e.g. only disk space alarms
Untested
None
=> chore: make monitoring config more granular

ansible/roles/dashmate/templates/dashmate.json.j2
Drive grove db operation log is missing actual grovedb operations
- Added drive grovedb operations to log specification string in dashmate config 
None
None
=> fix: drive log specification missing grovedb ops

ansible/roles/dashmate/templates/dashmate.json.j2
To do not duplicate data we should log only GroveDB operations with abci span. The span contains request ID that can be used to match operations with other data in elastic. 
- Log only grovedb operations
None
None
=> chore: log only grovedb operaions

ansible/roles/dashmate/templates/dashmate.json.j2
Dashmate v0.29.9 requires `core.docker.commandArgs` option in the config.
- Added `core.docker.commandArgs` option to the dashmate template
None
None
=> chore(dashmate): add `core.docker.commandArgs` option

ansible/roles/mn_createprotx/tasks/createprovidertx.yml, ansible/roles/mn_unban/tasks/createproupservtx.yml
Unban was failing with `error message: *_hpmn methods are deprecated. Use the related *_evo methods or set -deprecatedrpc=hpmn to enable them`
Change RPC calls to use `*_evo`
On testnet
None
=> fix: *_hpmn methods are deprecated. Use the related *_evo methods

test/smoke/quorum.js
Core v20 takes slightly longer to process a TX
Increase timeout
tests
None
=> fix: increase timeout on sendtx test

terraform/aws/instances.tf, terraform/aws/monitoring.tf, terraform/aws/variables.tf
Some small fixes, use a larger node type, fix variable typo, move mixers to the bottom of the monitoring concat to ensure 'overflow' issue does not happen
Run against testnet
None
=> chore: fix mixer nodes
